import 'package:flutter/gestures.dart' as lib;

import '../library.dart';

class GesturesLibrary extends FlutterLibrary {
  @override
  String get name => 'gestures';

  @override
  final List<String> widgets = [
  ];

  @override
  final Map<String, Function> classes = {
    'DelayedMultiDragGestureRecognizer': lib.DelayedMultiDragGestureRecognizer.new,
    'DeviceGestureSettings': lib.DeviceGestureSettings.new,
    'DeviceGestureSettings.fromView': lib.DeviceGestureSettings.fromView.call,
    'DiagnosticPropertiesBuilder': lib.DiagnosticPropertiesBuilder.new,
    'DiagnosticPropertiesBuilder.fromProperties': lib.DiagnosticPropertiesBuilder.fromProperties.call,
    'DoubleTapGestureRecognizer': lib.DoubleTapGestureRecognizer.new,
    'DragDownDetails': lib.DragDownDetails.new,
    'DragEndDetails': lib.DragEndDetails.new,
    'DragStartDetails': lib.DragStartDetails.new,
    'DragUpdateDetails': lib.DragUpdateDetails.new,
    'EagerGestureRecognizer': lib.EagerGestureRecognizer.new,
    'FlutterErrorDetailsForPointerEventDispatcher': lib.FlutterErrorDetailsForPointerEventDispatcher.new,
    'ForcePressDetails': lib.ForcePressDetails.new,
    'ForcePressGestureRecognizer': lib.ForcePressGestureRecognizer.new,
    'GestureArenaManager': lib.GestureArenaManager.new,
    'GestureArenaTeam': lib.GestureArenaTeam.new,
    'HitTestEntry': lib.HitTestEntry.new,
    'HitTestResult': lib.HitTestResult.new,
    'HitTestResult.wrap': lib.HitTestResult.wrap.call,
    'HorizontalDragGestureRecognizer': lib.HorizontalDragGestureRecognizer.new,
    'HorizontalMultiDragGestureRecognizer': lib.HorizontalMultiDragGestureRecognizer.new,
    'ImmediateMultiDragGestureRecognizer': lib.ImmediateMultiDragGestureRecognizer.new,
    'IOSScrollViewFlingVelocityTracker': lib.IOSScrollViewFlingVelocityTracker.new,
    'LeastSquaresSolver': lib.LeastSquaresSolver.new,
    'LongPressDownDetails': lib.LongPressDownDetails.new,
    'LongPressEndDetails': lib.LongPressEndDetails.new,
    'LongPressGestureRecognizer': lib.LongPressGestureRecognizer.new,
    'LongPressMoveUpdateDetails': lib.LongPressMoveUpdateDetails.new,
    'LongPressStartDetails': lib.LongPressStartDetails.new,
    'MacOSScrollViewFlingVelocityTracker': lib.MacOSScrollViewFlingVelocityTracker.new,
    'Matrix4': lib.Matrix4.new,
    'Matrix4.columns': lib.Matrix4.columns.call,
    'Matrix4.compose': lib.Matrix4.compose.call,
    'Matrix4.copy': lib.Matrix4.copy.call,
    'Matrix4.diagonal3': lib.Matrix4.diagonal3.call,
    'Matrix4.diagonal3Values': lib.Matrix4.diagonal3Values.call,
    'Matrix4.fromBuffer': lib.Matrix4.fromBuffer.call,
    'Matrix4.fromFloat64List': lib.Matrix4.fromFloat64List.call,
    'Matrix4.fromList': lib.Matrix4.fromList.call,
    'Matrix4.identity': lib.Matrix4.identity.call,
    'Matrix4.inverted': lib.Matrix4.inverted.call,
    'Matrix4.outer': lib.Matrix4.outer.call,
    'Matrix4.rotationX': lib.Matrix4.rotationX.call,
    'Matrix4.rotationY': lib.Matrix4.rotationY.call,
    'Matrix4.rotationZ': lib.Matrix4.rotationZ.call,
    'Matrix4.skew': lib.Matrix4.skew.call,
    'Matrix4.skewX': lib.Matrix4.skewX.call,
    'Matrix4.skewY': lib.Matrix4.skewY.call,
    'Matrix4.translation': lib.Matrix4.translation.call,
    'Matrix4.translationValues': lib.Matrix4.translationValues.call,
    'Matrix4.zero': lib.Matrix4.zero.call,
    'MultiTapGestureRecognizer': lib.MultiTapGestureRecognizer.new,
    'Offset': lib.Offset.new,
    'Offset.fromDirection': lib.Offset.fromDirection.call,
    'OffsetPair': lib.OffsetPair.new,
    'OffsetPair.fromEventDelta': lib.OffsetPair.fromEventDelta.call,
    'OffsetPair.fromEventPosition': lib.OffsetPair.fromEventPosition.call,
    'PanGestureRecognizer': lib.PanGestureRecognizer.new,
    'PointerAddedEvent': lib.PointerAddedEvent.new,
    'PointerCancelEvent': lib.PointerCancelEvent.new,
    'PointerData': lib.PointerData.new,
    'PointerDownEvent': lib.PointerDownEvent.new,
    'PointerEnterEvent': lib.PointerEnterEvent.new,
    'PointerEnterEvent.fromMouseEvent': lib.PointerEnterEvent.fromMouseEvent.call,
    'PointerEventResampler': lib.PointerEventResampler.new,
    'PointerExitEvent': lib.PointerExitEvent.new,
    'PointerExitEvent.fromMouseEvent': lib.PointerExitEvent.fromMouseEvent.call,
    'PointerHoverEvent': lib.PointerHoverEvent.new,
    'PointerMoveEvent': lib.PointerMoveEvent.new,
    'PointerPanZoomEndEvent': lib.PointerPanZoomEndEvent.new,
    'PointerPanZoomStartEvent': lib.PointerPanZoomStartEvent.new,
    'PointerPanZoomUpdateEvent': lib.PointerPanZoomUpdateEvent.new,
    'PointerRemovedEvent': lib.PointerRemovedEvent.new,
    'PointerRouter': lib.PointerRouter.new,
    'PointerScaleEvent': lib.PointerScaleEvent.new,
    'PointerScrollEvent': lib.PointerScrollEvent.new,
    'PointerScrollInertiaCancelEvent': lib.PointerScrollInertiaCancelEvent.new,
    'PointerSignalResolver': lib.PointerSignalResolver.new,
    'PointerUpEvent': lib.PointerUpEvent.new,
    'PolynomialFit': lib.PolynomialFit.new,
    'SamplingClock': lib.SamplingClock.new,
    'ScaleEndDetails': lib.ScaleEndDetails.new,
    'ScaleGestureRecognizer': lib.ScaleGestureRecognizer.new,
    'ScaleStartDetails': lib.ScaleStartDetails.new,
    'ScaleUpdateDetails': lib.ScaleUpdateDetails.new,
    'SerialTapCancelDetails': lib.SerialTapCancelDetails.new,
    'SerialTapDownDetails': lib.SerialTapDownDetails.new,
    'SerialTapGestureRecognizer': lib.SerialTapGestureRecognizer.new,
    'SerialTapUpDetails': lib.SerialTapUpDetails.new,
    'TapAndDragGestureRecognizer': lib.TapAndDragGestureRecognizer.new,
    'TapAndHorizontalDragGestureRecognizer': lib.TapAndHorizontalDragGestureRecognizer.new,
    'TapAndPanGestureRecognizer': lib.TapAndPanGestureRecognizer.new,
    'TapDownDetails': lib.TapDownDetails.new,
    'TapDragDownDetails': lib.TapDragDownDetails.new,
    'TapDragEndDetails': lib.TapDragEndDetails.new,
    'TapDragStartDetails': lib.TapDragStartDetails.new,
    'TapDragUpdateDetails': lib.TapDragUpdateDetails.new,
    'TapDragUpDetails': lib.TapDragUpDetails.new,
    'TapGestureRecognizer': lib.TapGestureRecognizer.new,
    'TapUpDetails': lib.TapUpDetails.new,
    'Velocity': lib.Velocity.new,
    'VelocityEstimate': lib.VelocityEstimate.new,
    'VelocityTracker.withKind': lib.VelocityTracker.withKind.call,
    'VerticalDragGestureRecognizer': lib.VerticalDragGestureRecognizer.new,
    'VerticalMultiDragGestureRecognizer': lib.VerticalMultiDragGestureRecognizer.new,
  };

  @override
  final Map<String, Function> functions = {
    'computeHitSlop': lib.computeHitSlop.call,
    'computePanSlop': lib.computePanSlop.call,
    'computeScaleSlop': lib.computeScaleSlop.call,
    'debugAssertAllGesturesVarsUnset': lib.debugAssertAllGesturesVarsUnset.call,
    'isSingleButton': lib.isSingleButton.call,
    'nthMouseButton': lib.nthMouseButton.call,
    'nthStylusButton': lib.nthStylusButton.call,
    'smallestButton': lib.smallestButton.call,
  };

  @override
  final Map<String, Object?> constants = {
    'kBackMouseButton': lib.kBackMouseButton,
    'kDefaultMouseScrollToScaleFactor': lib.kDefaultMouseScrollToScaleFactor,
    'kDefaultTrackpadScrollToScaleFactor': lib.kDefaultTrackpadScrollToScaleFactor,
    'kDoubleTapMinTime': lib.kDoubleTapMinTime,
    'kDoubleTapSlop': lib.kDoubleTapSlop,
    'kDoubleTapTimeout': lib.kDoubleTapTimeout,
    'kDoubleTapTouchSlop': lib.kDoubleTapTouchSlop,
    'kForwardMouseButton': lib.kForwardMouseButton,
    'kHoverTapSlop': lib.kHoverTapSlop,
    'kHoverTapTimeout': lib.kHoverTapTimeout,
    'kJumpTapTimeout': lib.kJumpTapTimeout,
    'kLongPressTimeout': lib.kLongPressTimeout,
    'kMaxFlingVelocity': lib.kMaxFlingVelocity,
    'kMiddleMouseButton': lib.kMiddleMouseButton,
    'kMinFlingVelocity': lib.kMinFlingVelocity,
    'kPagingTouchSlop': lib.kPagingTouchSlop,
    'kPanSlop': lib.kPanSlop,
    'kPrecisePointerHitSlop': lib.kPrecisePointerHitSlop,
    'kPrecisePointerPanSlop': lib.kPrecisePointerPanSlop,
    'kPrecisePointerScaleSlop': lib.kPrecisePointerScaleSlop,
    'kPressTimeout': lib.kPressTimeout,
    'kPrimaryButton': lib.kPrimaryButton,
    'kPrimaryMouseButton': lib.kPrimaryMouseButton,
    'kPrimaryStylusButton': lib.kPrimaryStylusButton,
    'kScaleSlop': lib.kScaleSlop,
    'kSecondaryButton': lib.kSecondaryButton,
    'kSecondaryMouseButton': lib.kSecondaryMouseButton,
    'kSecondaryStylusButton': lib.kSecondaryStylusButton,
    'kStylusContact': lib.kStylusContact,
    'kTertiaryButton': lib.kTertiaryButton,
    'kTouchContact': lib.kTouchContact,
    'kTouchSlop': lib.kTouchSlop,
    'kWindowTouchSlop': lib.kWindowTouchSlop,
    'kZoomControlsTimeout': lib.kZoomControlsTimeout,
  };

  @override
  final Map<String, List<Enum>> enums = {
    'DragStartBehavior': lib.DragStartBehavior.values,
    'GestureDisposition': lib.GestureDisposition.values,
    'GestureRecognizerState': lib.GestureRecognizerState.values,
    'MultitouchDragStrategy': lib.MultitouchDragStrategy.values,
    'PointerDeviceKind': lib.PointerDeviceKind.values,
  };
 
  @override
  final Map<String, Map<String, Object? Function()>> statics = {
    'Offset': {
      'infinite': () => lib.Offset.infinite,
      'zero': () => lib.Offset.zero,
    },
    'OffsetPair': {
      'zero': () => lib.OffsetPair.zero,
    },
    'Velocity': {
      'zero': () => lib.Velocity.zero,
    },
  };
}
