import 'package:flutter/rendering.dart' as lib;

import '../library.dart';

class RenderingLibrary extends FlutterLibrary {
  @override
  String get name => 'rendering';

  @override
  final List<String> widgets = [
  ];

  @override
  final Map<String, Function> classes = {
    'Accumulator': lib.Accumulator.new,
    'Alignment': lib.Alignment.new,
    'AlignmentDirectional': lib.AlignmentDirectional.new,
    'AlignmentGeometryTween': lib.AlignmentGeometryTween.new,
    'AlignmentTween': lib.AlignmentTween.new,
    'AnnotatedRegionLayer': lib.AnnotatedRegionLayer.new,
    'AnnotationEntry': lib.AnnotationEntry.new,
    'AnnotationResult': lib.AnnotationResult.new,
    'AnnounceSemanticsEvent': lib.AnnounceSemanticsEvent.new,
    'AssetBundleImageKey': lib.AssetBundleImageKey.new,
    'AssetImage': lib.AssetImage.new,
    'AttributedString': lib.AttributedString.new,
    'AttributedStringProperty': lib.AttributedStringProperty.new,
    'AutomaticNotchedShape': lib.AutomaticNotchedShape.new,
    'BackdropFilterLayer': lib.BackdropFilterLayer.new,
    'BeveledRectangleBorder': lib.BeveledRectangleBorder.new,
    'Border': lib.Border.new,
    'Border.all': lib.Border.all.call,
    'Border.fromBorderSide': lib.Border.fromBorderSide.call,
    'Border.symmetric': lib.Border.symmetric.call,
    'BorderDirectional': lib.BorderDirectional.new,
    'BorderRadius.all': lib.BorderRadius.all.call,
    'BorderRadius.circular': lib.BorderRadius.circular.call,
    'BorderRadius.horizontal': lib.BorderRadius.horizontal.call,
    'BorderRadius.only': lib.BorderRadius.only.call,
    'BorderRadius.vertical': lib.BorderRadius.vertical.call,
    'BorderRadiusDirectional.all': lib.BorderRadiusDirectional.all.call,
    'BorderRadiusDirectional.circular': lib.BorderRadiusDirectional.circular.call,
    'BorderRadiusDirectional.horizontal': lib.BorderRadiusDirectional.horizontal.call,
    'BorderRadiusDirectional.only': lib.BorderRadiusDirectional.only.call,
    'BorderRadiusDirectional.vertical': lib.BorderRadiusDirectional.vertical.call,
    'BorderSide': lib.BorderSide.new,
    'BoxConstraints': lib.BoxConstraints.new,
    'BoxConstraints.expand': lib.BoxConstraints.expand.call,
    'BoxConstraints.fromViewConstraints': lib.BoxConstraints.fromViewConstraints.call,
    'BoxConstraints.loose': lib.BoxConstraints.loose.call,
    'BoxConstraints.tight': lib.BoxConstraints.tight.call,
    'BoxConstraints.tightFor': lib.BoxConstraints.tightFor.call,
    'BoxConstraints.tightForFinite': lib.BoxConstraints.tightForFinite.call,
    'BoxDecoration': lib.BoxDecoration.new,
    'BoxHitTestEntry': lib.BoxHitTestEntry.new,
    'BoxHitTestResult': lib.BoxHitTestResult.new,
    'BoxHitTestResult.wrap': lib.BoxHitTestResult.wrap.call,
    'BoxParentData': lib.BoxParentData.new,
    'BoxShadow': lib.BoxShadow.new,
    'ChildSemanticsConfigurationsResultBuilder': lib.ChildSemanticsConfigurationsResultBuilder.new,
    'CircleBorder': lib.CircleBorder.new,
    'CircularNotchedRectangle': lib.CircularNotchedRectangle.new,
    'ClearSelectionEvent': lib.ClearSelectionEvent.new,
    'ClipPathLayer': lib.ClipPathLayer.new,
    'ClipRectLayer': lib.ClipRectLayer.new,
    'ClipRRectLayer': lib.ClipRRectLayer.new,
    'Color': lib.Color.new,
    'Color.fromARGB': lib.Color.fromARGB.call,
    'Color.fromRGBO': lib.Color.fromRGBO.call,
    'ColorFilter.linearToSrgbGamma': lib.ColorFilter.linearToSrgbGamma.call,
    'ColorFilter.matrix': lib.ColorFilter.matrix.call,
    'ColorFilter.mode': lib.ColorFilter.mode.call,
    'ColorFilter.srgbToLinearGamma': lib.ColorFilter.srgbToLinearGamma.call,
    'ColorFilterLayer': lib.ColorFilterLayer.new,
    'ColorProperty': lib.ColorProperty.new,
    'ColorSwatch': lib.ColorSwatch.new,
    'ContainerLayer': lib.ContainerLayer.new,
    'ContinuousRectangleBorder': lib.ContinuousRectangleBorder.new,
    'CustomPainterSemantics': lib.CustomPainterSemantics.new,
    'CustomSemanticsAction': lib.CustomSemanticsAction.new,
    'CustomSemanticsAction.overridingAction': lib.CustomSemanticsAction.overridingAction.call,
    'DecorationImage': lib.DecorationImage.new,
    'DiagnosticPropertiesBuilder': lib.DiagnosticPropertiesBuilder.new,
    'DiagnosticPropertiesBuilder.fromProperties': lib.DiagnosticPropertiesBuilder.fromProperties.call,
    'DiagnosticsDebugCreator': lib.DiagnosticsDebugCreator.new,
    'DiagnosticsProperty': lib.DiagnosticsProperty.new,
    'DiagnosticsProperty.lazy': lib.DiagnosticsProperty.lazy.call,
    'DirectionallyExtendSelectionEvent': lib.DirectionallyExtendSelectionEvent.new,
    'DoubleProperty': lib.DoubleProperty.new,
    'DoubleProperty.lazy': lib.DoubleProperty.lazy.call,
    'EdgeInsets.all': lib.EdgeInsets.all.call,
    'EdgeInsets.fromLTRB': lib.EdgeInsets.fromLTRB.call,
    'EdgeInsets.fromViewPadding': lib.EdgeInsets.fromViewPadding.call,
    'EdgeInsets.fromWindowPadding': lib.EdgeInsets.fromWindowPadding.call,
    'EdgeInsets.only': lib.EdgeInsets.only.call,
    'EdgeInsets.symmetric': lib.EdgeInsets.symmetric.call,
    'EdgeInsetsDirectional.all': lib.EdgeInsetsDirectional.all.call,
    'EdgeInsetsDirectional.fromSTEB': lib.EdgeInsetsDirectional.fromSTEB.call,
    'EdgeInsetsDirectional.only': lib.EdgeInsetsDirectional.only.call,
    'EdgeInsetsDirectional.symmetric': lib.EdgeInsetsDirectional.symmetric.call,
    'EnumProperty': lib.EnumProperty.new,
    'ErrorDescription': lib.ErrorDescription.new,
    'ErrorHint': lib.ErrorHint.new,
    'ErrorSummary': lib.ErrorSummary.new,
    'ExactAssetImage': lib.ExactAssetImage.new,
    'FileImage': lib.FileImage.new,
    'FittedSizes': lib.FittedSizes.new,
    'FixedColumnWidth': lib.FixedColumnWidth.new,
    'FlagProperty': lib.FlagProperty.new,
    'FlexColumnWidth': lib.FlexColumnWidth.new,
    'FlexParentData': lib.FlexParentData.new,
    'FloatingHeaderSnapConfiguration': lib.FloatingHeaderSnapConfiguration.new,
    'FlowParentData': lib.FlowParentData.new,
    'FlutterLogoDecoration': lib.FlutterLogoDecoration.new,
    'FocusSemanticEvent': lib.FocusSemanticEvent.new,
    'FollowerLayer': lib.FollowerLayer.new,
    'FontFeature': lib.FontFeature.new,
    'FontFeature.alternative': lib.FontFeature.alternative.call,
    'FontFeature.alternativeFractions': lib.FontFeature.alternativeFractions.call,
    'FontFeature.caseSensitiveForms': lib.FontFeature.caseSensitiveForms.call,
    'FontFeature.characterVariant': lib.FontFeature.characterVariant.call,
    'FontFeature.contextualAlternates': lib.FontFeature.contextualAlternates.call,
    'FontFeature.denominator': lib.FontFeature.denominator.call,
    'FontFeature.disable': lib.FontFeature.disable.call,
    'FontFeature.enable': lib.FontFeature.enable.call,
    'FontFeature.fractions': lib.FontFeature.fractions.call,
    'FontFeature.historicalForms': lib.FontFeature.historicalForms.call,
    'FontFeature.historicalLigatures': lib.FontFeature.historicalLigatures.call,
    'FontFeature.liningFigures': lib.FontFeature.liningFigures.call,
    'FontFeature.localeAware': lib.FontFeature.localeAware.call,
    'FontFeature.notationalForms': lib.FontFeature.notationalForms.call,
    'FontFeature.numerators': lib.FontFeature.numerators.call,
    'FontFeature.oldstyleFigures': lib.FontFeature.oldstyleFigures.call,
    'FontFeature.ordinalForms': lib.FontFeature.ordinalForms.call,
    'FontFeature.proportionalFigures': lib.FontFeature.proportionalFigures.call,
    'FontFeature.randomize': lib.FontFeature.randomize.call,
    'FontFeature.scientificInferiors': lib.FontFeature.scientificInferiors.call,
    'FontFeature.slashedZero': lib.FontFeature.slashedZero.call,
    'FontFeature.stylisticAlternates': lib.FontFeature.stylisticAlternates.call,
    'FontFeature.stylisticSet': lib.FontFeature.stylisticSet.call,
    'FontFeature.subscripts': lib.FontFeature.subscripts.call,
    'FontFeature.superscripts': lib.FontFeature.superscripts.call,
    'FontFeature.swash': lib.FontFeature.swash.call,
    'FontFeature.tabularFigures': lib.FontFeature.tabularFigures.call,
    'FontVariation': lib.FontVariation.new,
    'FontVariation.italic': lib.FontVariation.italic.call,
    'FontVariation.opticalSize': lib.FontVariation.opticalSize.call,
    'FontVariation.slant': lib.FontVariation.slant.call,
    'FontVariation.weight': lib.FontVariation.weight.call,
    'FontVariation.width': lib.FontVariation.width.call,
    'FractionalOffset': lib.FractionalOffset.new,
    'FractionalOffset.fromOffsetAndRect': lib.FractionalOffset.fromOffsetAndRect.call,
    'FractionalOffset.fromOffsetAndSize': lib.FractionalOffset.fromOffsetAndSize.call,
    'FractionalOffsetTween': lib.FractionalOffsetTween.new,
    'FractionColumnWidth': lib.FractionColumnWidth.new,
    'GlyphInfo': lib.GlyphInfo.new,
    'GradientRotation': lib.GradientRotation.new,
    'GranularlyExtendSelectionEvent': lib.GranularlyExtendSelectionEvent.new,
    'HitTestEntry': lib.HitTestEntry.new,
    'HitTestResult': lib.HitTestResult.new,
    'HitTestResult.wrap': lib.HitTestResult.wrap.call,
    'HSLColor.fromAHSL': lib.HSLColor.fromAHSL.call,
    'HSLColor.fromColor': lib.HSLColor.fromColor.call,
    'HSVColor.fromAHSV': lib.HSVColor.fromAHSV.call,
    'HSVColor.fromColor': lib.HSVColor.fromColor.call,
    'ImageCache': lib.ImageCache.new,
    'ImageChunkEvent': lib.ImageChunkEvent.new,
    'ImageConfiguration': lib.ImageConfiguration.new,
    'ImageFilterLayer': lib.ImageFilterLayer.new,
    'ImageInfo': lib.ImageInfo.new,
    'ImageShader': lib.ImageShader.new,
    'ImageSizeInfo': lib.ImageSizeInfo.new,
    'ImageStream': lib.ImageStream.new,
    'ImageStreamListener': lib.ImageStreamListener.new,
    'InlineSpanSemanticsInformation': lib.InlineSpanSemanticsInformation.new,
    'IntProperty': lib.IntProperty.new,
    'IntrinsicColumnWidth': lib.IntrinsicColumnWidth.new,
    'LayerHandle': lib.LayerHandle.new,
    'LayerLink': lib.LayerLink.new,
    'LeaderLayer': lib.LeaderLayer.new,
    'LinearBorder': lib.LinearBorder.new,
    'LinearBorder.bottom': lib.LinearBorder.bottom.call,
    'LinearBorder.end': lib.LinearBorder.end.call,
    'LinearBorder.start': lib.LinearBorder.start.call,
    'LinearBorder.top': lib.LinearBorder.top.call,
    'LinearBorderEdge': lib.LinearBorderEdge.new,
    'LinearGradient': lib.LinearGradient.new,
    'LineMetrics': lib.LineMetrics.new,
    'ListBodyParentData': lib.ListBodyParentData.new,
    'ListWheelParentData': lib.ListWheelParentData.new,
    'Locale': lib.Locale.new,
    'Locale.fromSubtags': lib.Locale.fromSubtags.call,
    'LocaleStringAttribute': lib.LocaleStringAttribute.new,
    'LongPressSemanticsEvent': lib.LongPressSemanticsEvent.new,
    'MaskFilter.blur': lib.MaskFilter.blur.call,
    'Matrix4': lib.Matrix4.new,
    'Matrix4.columns': lib.Matrix4.columns.call,
    'Matrix4.compose': lib.Matrix4.compose.call,
    'Matrix4.copy': lib.Matrix4.copy.call,
    'Matrix4.diagonal3': lib.Matrix4.diagonal3.call,
    'Matrix4.diagonal3Values': lib.Matrix4.diagonal3Values.call,
    'Matrix4.fromBuffer': lib.Matrix4.fromBuffer.call,
    'Matrix4.fromFloat64List': lib.Matrix4.fromFloat64List.call,
    'Matrix4.fromList': lib.Matrix4.fromList.call,
    'Matrix4.identity': lib.Matrix4.identity.call,
    'Matrix4.inverted': lib.Matrix4.inverted.call,
    'Matrix4.outer': lib.Matrix4.outer.call,
    'Matrix4.rotationX': lib.Matrix4.rotationX.call,
    'Matrix4.rotationY': lib.Matrix4.rotationY.call,
    'Matrix4.rotationZ': lib.Matrix4.rotationZ.call,
    'Matrix4.skew': lib.Matrix4.skew.call,
    'Matrix4.skewX': lib.Matrix4.skewX.call,
    'Matrix4.skewY': lib.Matrix4.skewY.call,
    'Matrix4.translation': lib.Matrix4.translation.call,
    'Matrix4.translationValues': lib.Matrix4.translationValues.call,
    'Matrix4.zero': lib.Matrix4.zero.call,
    'MaxColumnWidth': lib.MaxColumnWidth.new,
    'MemoryImage': lib.MemoryImage.new,
    'MinColumnWidth': lib.MinColumnWidth.new,
    'MouseTracker': lib.MouseTracker.new,
    'MultiChildLayoutParentData': lib.MultiChildLayoutParentData.new,
    'MultiFrameImageStreamCompleter': lib.MultiFrameImageStreamCompleter.new,
    'Offset': lib.Offset.new,
    'Offset.fromDirection': lib.Offset.fromDirection.call,
    'OffsetLayer': lib.OffsetLayer.new,
    'OneFrameImageStreamCompleter': lib.OneFrameImageStreamCompleter.new,
    'OpacityLayer': lib.OpacityLayer.new,
    'OrdinalSortKey': lib.OrdinalSortKey.new,
    'OvalBorder': lib.OvalBorder.new,
    'OverScrollHeaderStretchConfiguration': lib.OverScrollHeaderStretchConfiguration.new,
    'Paint': lib.Paint.new,
    'Paint.from': lib.Paint.from.call,
    'PaintingContext': lib.PaintingContext.new,
    'ParentData': lib.ParentData.new,
    'PerformanceOverlayLayer': lib.PerformanceOverlayLayer.new,
    'PersistentHeaderShowOnScreenConfiguration': lib.PersistentHeaderShowOnScreenConfiguration.new,
    'PictureLayer': lib.PictureLayer.new,
    'PipelineOwner': lib.PipelineOwner.new,
    'PlaceholderDimensions': lib.PlaceholderDimensions.new,
    'PlaceholderSpanIndexSemanticsTag': lib.PlaceholderSpanIndexSemanticsTag.new,
    'PlatformViewLayer': lib.PlatformViewLayer.new,
    'PlatformViewRenderBox': lib.PlatformViewRenderBox.new,
    'PointerCancelEvent': lib.PointerCancelEvent.new,
    'PointerDownEvent': lib.PointerDownEvent.new,
    'PointerMoveEvent': lib.PointerMoveEvent.new,
    'PointerUpEvent': lib.PointerUpEvent.new,
    'RadialGradient': lib.RadialGradient.new,
    'Radius.circular': lib.Radius.circular.call,
    'Radius.elliptical': lib.Radius.elliptical.call,
    'Rect.fromCenter': lib.Rect.fromCenter.call,
    'Rect.fromCircle': lib.Rect.fromCircle.call,
    'Rect.fromLTRB': lib.Rect.fromLTRB.call,
    'Rect.fromLTWH': lib.Rect.fromLTWH.call,
    'Rect.fromPoints': lib.Rect.fromPoints.call,
    'RelativeRect.fromDirectional': lib.RelativeRect.fromDirectional.call,
    'RelativeRect.fromLTRB': lib.RelativeRect.fromLTRB.call,
    'RelativeRect.fromRect': lib.RelativeRect.fromRect.call,
    'RelativeRect.fromSize': lib.RelativeRect.fromSize.call,
    'RenderAbsorbPointer': lib.RenderAbsorbPointer.new,
    'RenderAndroidView': lib.RenderAndroidView.new,
    'RenderAnimatedOpacity': lib.RenderAnimatedOpacity.new,
    'RenderAnimatedSize': lib.RenderAnimatedSize.new,
    'RenderAnnotatedRegion': lib.RenderAnnotatedRegion.new,
    'RenderAppKitView': lib.RenderAppKitView.new,
    'RenderAspectRatio': lib.RenderAspectRatio.new,
    'RenderBackdropFilter': lib.RenderBackdropFilter.new,
    'RenderBaseline': lib.RenderBaseline.new,
    'RenderBlockSemantics': lib.RenderBlockSemantics.new,
    'RenderClipOval': lib.RenderClipOval.new,
    'RenderClipPath': lib.RenderClipPath.new,
    'RenderClipRect': lib.RenderClipRect.new,
    'RenderClipRRect': lib.RenderClipRRect.new,
    'RenderConstrainedBox': lib.RenderConstrainedBox.new,
    'RenderConstrainedOverflowBox': lib.RenderConstrainedOverflowBox.new,
    'RenderConstraintsTransformBox': lib.RenderConstraintsTransformBox.new,
    'RenderCustomMultiChildLayoutBox': lib.RenderCustomMultiChildLayoutBox.new,
    'RenderCustomPaint': lib.RenderCustomPaint.new,
    'RenderCustomSingleChildLayoutBox': lib.RenderCustomSingleChildLayoutBox.new,
    'RenderDecoratedBox': lib.RenderDecoratedBox.new,
    'RenderDecoratedSliver': lib.RenderDecoratedSliver.new,
    'RenderEditable': lib.RenderEditable.new,
    'RenderErrorBox': lib.RenderErrorBox.new,
    'RenderExcludeSemantics': lib.RenderExcludeSemantics.new,
    'RenderFittedBox': lib.RenderFittedBox.new,
    'RenderFlex': lib.RenderFlex.new,
    'RenderFlow': lib.RenderFlow.new,
    'RenderFollowerLayer': lib.RenderFollowerLayer.new,
    'RenderFractionallySizedOverflowBox': lib.RenderFractionallySizedOverflowBox.new,
    'RenderFractionalTranslation': lib.RenderFractionalTranslation.new,
    'RenderIgnoreBaseline': lib.RenderIgnoreBaseline.new,
    'RenderIgnorePointer': lib.RenderIgnorePointer.new,
    'RenderImage': lib.RenderImage.new,
    'RenderIndexedSemantics': lib.RenderIndexedSemantics.new,
    'RenderIndexedStack': lib.RenderIndexedStack.new,
    'RenderingFlutterBinding': lib.RenderingFlutterBinding.new,
    'RenderIntrinsicHeight': lib.RenderIntrinsicHeight.new,
    'RenderIntrinsicWidth': lib.RenderIntrinsicWidth.new,
    'RenderLeaderLayer': lib.RenderLeaderLayer.new,
    'RenderLimitedBox': lib.RenderLimitedBox.new,
    'RenderListBody': lib.RenderListBody.new,
    'RenderListWheelViewport': lib.RenderListWheelViewport.new,
    'RenderMergeSemantics': lib.RenderMergeSemantics.new,
    'RenderMetaData': lib.RenderMetaData.new,
    'RenderMouseRegion': lib.RenderMouseRegion.new,
    'RenderOffstage': lib.RenderOffstage.new,
    'RenderOpacity': lib.RenderOpacity.new,
    'RenderPadding': lib.RenderPadding.new,
    'RenderParagraph': lib.RenderParagraph.new,
    'RenderPerformanceOverlay': lib.RenderPerformanceOverlay.new,
    'RenderPhysicalModel': lib.RenderPhysicalModel.new,
    'RenderPhysicalShape': lib.RenderPhysicalShape.new,
    'RenderPointerListener': lib.RenderPointerListener.new,
    'RenderPositionedBox': lib.RenderPositionedBox.new,
    'RenderProxyBox': lib.RenderProxyBox.new,
    'RenderRepaintBoundary': lib.RenderRepaintBoundary.new,
    'RenderRotatedBox': lib.RenderRotatedBox.new,
    'RenderSemanticsAnnotations': lib.RenderSemanticsAnnotations.new,
    'RenderSemanticsGestureHandler': lib.RenderSemanticsGestureHandler.new,
    'RenderShaderMask': lib.RenderShaderMask.new,
    'RenderShrinkWrappingViewport': lib.RenderShrinkWrappingViewport.new,
    'RenderSizedOverflowBox': lib.RenderSizedOverflowBox.new,
    'RenderSliverAnimatedOpacity': lib.RenderSliverAnimatedOpacity.new,
    'RenderSliverConstrainedCrossAxis': lib.RenderSliverConstrainedCrossAxis.new,
    'RenderSliverCrossAxisGroup': lib.RenderSliverCrossAxisGroup.new,
    'RenderSliverFillRemaining': lib.RenderSliverFillRemaining.new,
    'RenderSliverFillRemainingAndOverscroll': lib.RenderSliverFillRemainingAndOverscroll.new,
    'RenderSliverFillRemainingWithScrollable': lib.RenderSliverFillRemainingWithScrollable.new,
    'RenderSliverFillViewport': lib.RenderSliverFillViewport.new,
    'RenderSliverFixedExtentList': lib.RenderSliverFixedExtentList.new,
    'RenderSliverGrid': lib.RenderSliverGrid.new,
    'RenderSliverIgnorePointer': lib.RenderSliverIgnorePointer.new,
    'RenderSliverList': lib.RenderSliverList.new,
    'RenderSliverMainAxisGroup': lib.RenderSliverMainAxisGroup.new,
    'RenderSliverOffstage': lib.RenderSliverOffstage.new,
    'RenderSliverOpacity': lib.RenderSliverOpacity.new,
    'RenderSliverPadding': lib.RenderSliverPadding.new,
    'RenderSliverToBoxAdapter': lib.RenderSliverToBoxAdapter.new,
    'RenderSliverVariedExtentList': lib.RenderSliverVariedExtentList.new,
    'RenderStack': lib.RenderStack.new,
    'RenderTable': lib.RenderTable.new,
    'RenderTransform': lib.RenderTransform.new,
    'RenderTreeSliver': lib.RenderTreeSliver.new,
    'RenderUiKitView': lib.RenderUiKitView.new,
    'RenderView': lib.RenderView.new,
    'RenderViewport': lib.RenderViewport.new,
    'RenderWrap': lib.RenderWrap.new,
    'ResizeImage': lib.ResizeImage.new,
    'RevealedOffset': lib.RevealedOffset.new,
    'RoundedRectangleBorder': lib.RoundedRectangleBorder.new,
    'RRect.fromLTRBAndCorners': lib.RRect.fromLTRBAndCorners.call,
    'RRect.fromLTRBR': lib.RRect.fromLTRBR.call,
    'RRect.fromLTRBXY': lib.RRect.fromLTRBXY.call,
    'RRect.fromRectAndCorners': lib.RRect.fromRectAndCorners.call,
    'RRect.fromRectAndRadius': lib.RRect.fromRectAndRadius.call,
    'RRect.fromRectXY': lib.RRect.fromRectXY.call,
    'RSTransform': lib.RSTransform.new,
    'RSTransform.fromComponents': lib.RSTransform.fromComponents.call,
    'SelectAllSelectionEvent': lib.SelectAllSelectionEvent.new,
    'SelectedContent': lib.SelectedContent.new,
    'SelectionEdgeUpdateEvent.forEnd': lib.SelectionEdgeUpdateEvent.forEnd.call,
    'SelectionEdgeUpdateEvent.forStart': lib.SelectionEdgeUpdateEvent.forStart.call,
    'SelectionGeometry': lib.SelectionGeometry.new,
    'SelectionPoint': lib.SelectionPoint.new,
    'SelectParagraphSelectionEvent': lib.SelectParagraphSelectionEvent.new,
    'SelectWordSelectionEvent': lib.SelectWordSelectionEvent.new,
    'SemanticsActionEvent': lib.SemanticsActionEvent.new,
    'SemanticsConfiguration': lib.SemanticsConfiguration.new,
    'SemanticsData': lib.SemanticsData.new,
    'SemanticsHintOverrides': lib.SemanticsHintOverrides.new,
    'SemanticsNode': lib.SemanticsNode.new,
    'SemanticsNode.root': lib.SemanticsNode.root.call,
    'SemanticsOwner': lib.SemanticsOwner.new,
    'SemanticsProperties': lib.SemanticsProperties.new,
    'SemanticsTag': lib.SemanticsTag.new,
    'ShaderMaskLayer': lib.ShaderMaskLayer.new,
    'Shadow': lib.Shadow.new,
    'ShapeBorderClipper': lib.ShapeBorderClipper.new,
    'ShapeDecoration': lib.ShapeDecoration.new,
    'ShapeDecoration.fromBoxDecoration': lib.ShapeDecoration.fromBoxDecoration.call,
    'Size': lib.Size.new,
    'Size.copy': lib.Size.copy.call,
    'Size.fromHeight': lib.Size.fromHeight.call,
    'Size.fromRadius': lib.Size.fromRadius.call,
    'Size.fromWidth': lib.Size.fromWidth.call,
    'Size.square': lib.Size.square.call,
    'SliverConstraints': lib.SliverConstraints.new,
    'SliverGeometry': lib.SliverGeometry.new,
    'SliverGridDelegateWithFixedCrossAxisCount': lib.SliverGridDelegateWithFixedCrossAxisCount.new,
    'SliverGridDelegateWithMaxCrossAxisExtent': lib.SliverGridDelegateWithMaxCrossAxisExtent.new,
    'SliverGridGeometry': lib.SliverGridGeometry.new,
    'SliverGridParentData': lib.SliverGridParentData.new,
    'SliverGridRegularTileLayout': lib.SliverGridRegularTileLayout.new,
    'SliverHitTestEntry': lib.SliverHitTestEntry.new,
    'SliverHitTestResult': lib.SliverHitTestResult.new,
    'SliverHitTestResult.wrap': lib.SliverHitTestResult.wrap.call,
    'SliverLayoutDimensions': lib.SliverLayoutDimensions.new,
    'SliverLogicalContainerParentData': lib.SliverLogicalContainerParentData.new,
    'SliverLogicalParentData': lib.SliverLogicalParentData.new,
    'SliverMultiBoxAdaptorParentData': lib.SliverMultiBoxAdaptorParentData.new,
    'SliverPhysicalContainerParentData': lib.SliverPhysicalContainerParentData.new,
    'SliverPhysicalParentData': lib.SliverPhysicalParentData.new,
    'SpellOutStringAttribute': lib.SpellOutStringAttribute.new,
    'StackParentData': lib.StackParentData.new,
    'StadiumBorder': lib.StadiumBorder.new,
    'StarBorder': lib.StarBorder.new,
    'StarBorder.polygon': lib.StarBorder.polygon.call,
    'StringProperty': lib.StringProperty.new,
    'StrutStyle': lib.StrutStyle.new,
    'StrutStyle.fromTextStyle': lib.StrutStyle.fromTextStyle.call,
    'SweepGradient': lib.SweepGradient.new,
    'TableBorder': lib.TableBorder.new,
    'TableBorder.all': lib.TableBorder.all.call,
    'TableBorder.symmetric': lib.TableBorder.symmetric.call,
    'TableCellParentData': lib.TableCellParentData.new,
    'TapSemanticEvent': lib.TapSemanticEvent.new,
    'TextAlignVertical': lib.TextAlignVertical.new,
    'TextBox.fromLTRBD': lib.TextBox.fromLTRBD.call,
    'TextDecoration.combine': lib.TextDecoration.combine.call,
    'TextHeightBehavior': lib.TextHeightBehavior.new,
    'TextPainter': lib.TextPainter.new,
    'TextParentData': lib.TextParentData.new,
    'TextPosition': lib.TextPosition.new,
    'TextRange': lib.TextRange.new,
    'TextRange.collapsed': lib.TextRange.collapsed.call,
    'TextSelection': lib.TextSelection.new,
    'TextSelection.collapsed': lib.TextSelection.collapsed.call,
    'TextSelection.fromPosition': lib.TextSelection.fromPosition.call,
    'TextSelectionPoint': lib.TextSelectionPoint.new,
    'TextSpan': lib.TextSpan.new,
    'TextStyle': lib.TextStyle.new,
    'TextTreeConfiguration': lib.TextTreeConfiguration.new,
    'TextureBox': lib.TextureBox.new,
    'TextureLayer': lib.TextureLayer.new,
    'TooltipSemanticsEvent': lib.TooltipSemanticsEvent.new,
    'TransformLayer': lib.TransformLayer.new,
    'TransformProperty': lib.TransformProperty.new,
    'TreeSliverNodeParentData': lib.TreeSliverNodeParentData.new,
    'ViewConfiguration': lib.ViewConfiguration.new,
    'ViewConfiguration.fromView': lib.ViewConfiguration.fromView.call,
    'WrapParentData': lib.WrapParentData.new,
  };

  @override
  final Map<String, Function> functions = {
    'applyBoxFit': lib.applyBoxFit.call,
    'applyGrowthDirectionToAxisDirection': lib.applyGrowthDirectionToAxisDirection.call,
    'applyGrowthDirectionToScrollDirection': lib.applyGrowthDirectionToScrollDirection.call,
    'axisDirectionIsReversed': lib.axisDirectionIsReversed.call,
    'axisDirectionToAxis': lib.axisDirectionToAxis.call,
    'combineSemanticsInfo': lib.combineSemanticsInfo.call,
    'debugAssertAllPaintingVarsUnset': lib.debugAssertAllPaintingVarsUnset.call,
    'debugAssertAllRenderVarsUnset': lib.debugAssertAllRenderVarsUnset.call,
    'debugCheckHasBoundedAxis': lib.debugCheckHasBoundedAxis.call,
    'debugDescribeTransform': lib.debugDescribeTransform.call,
    'debugDumpLayerTree': lib.debugDumpLayerTree.call,
    'debugDumpPipelineOwnerTree': lib.debugDumpPipelineOwnerTree.call,
    'debugDumpRenderTree': lib.debugDumpRenderTree.call,
    'debugDumpSemanticsTree': lib.debugDumpSemanticsTree.call,
    'debugFlushLastFrameImageSizeInfo': lib.debugFlushLastFrameImageSizeInfo.call,
    'debugPaintPadding': lib.debugPaintPadding.call,
    'debugResetSemanticsIdCounter': lib.debugResetSemanticsIdCounter.call,
    'decodeImageFromList': lib.decodeImageFromList.call,
    'flipAxis': lib.flipAxis.call,
    'flipAxisDirection': lib.flipAxisDirection.call,
    'flipScrollDirection': lib.flipScrollDirection.call,
    'hashList': lib.hashList.call,
    'hashValues': lib.hashValues.call,
    'lerpFontVariations': lib.lerpFontVariations.call,
    'paintBorder': lib.paintBorder.call,
    'paintImage': lib.paintImage.call,
    'paintZigZag': lib.paintZigZag.call,
    'positionDependentBox': lib.positionDependentBox.call,
    'textDirectionToAxisDirection': lib.textDirectionToAxisDirection.call,
  };

  @override
  final Map<String, Object?> constants = {
    'kDefaultFontSize': lib.kDefaultFontSize,
    'kTextHeightNone': lib.kTextHeightNone,
  };

  @override
  final Map<String, List<Enum>> enums = {
    'Assertiveness': lib.Assertiveness.values,
    'Axis': lib.Axis.values,
    'AxisDirection': lib.AxisDirection.values,
    'BlendMode': lib.BlendMode.values,
    'BlurStyle': lib.BlurStyle.values,
    'BorderStyle': lib.BorderStyle.values,
    'BoxFit': lib.BoxFit.values,
    'BoxShape': lib.BoxShape.values,
    'CacheExtentStyle': lib.CacheExtentStyle.values,
    'Clip': lib.Clip.values,
    'CrossAxisAlignment': lib.CrossAxisAlignment.values,
    'DebugSemanticsDumpOrder': lib.DebugSemanticsDumpOrder.values,
    'DecorationPosition': lib.DecorationPosition.values,
    'DiagnosticLevel': lib.DiagnosticLevel.values,
    'DiagnosticsTreeStyle': lib.DiagnosticsTreeStyle.values,
    'FilterQuality': lib.FilterQuality.values,
    'FlexFit': lib.FlexFit.values,
    'FlutterLogoStyle': lib.FlutterLogoStyle.values,
    'FontStyle': lib.FontStyle.values,
    'GrowthDirection': lib.GrowthDirection.values,
    'HitTestBehavior': lib.HitTestBehavior.values,
    'ImageRepeat': lib.ImageRepeat.values,
    'MainAxisAlignment': lib.MainAxisAlignment.values,
    'MainAxisSize': lib.MainAxisSize.values,
    'OverflowBoxFit': lib.OverflowBoxFit.values,
    'PaintingStyle': lib.PaintingStyle.values,
    'PathFillType': lib.PathFillType.values,
    'PathOperation': lib.PathOperation.values,
    'PerformanceOverlayOption': lib.PerformanceOverlayOption.values,
    'PlaceholderAlignment': lib.PlaceholderAlignment.values,
    'PlatformViewHitTestBehavior': lib.PlatformViewHitTestBehavior.values,
    'RenderAnimatedSizeState': lib.RenderAnimatedSizeState.values,
    'RenderComparison': lib.RenderComparison.values,
    'RenderingServiceExtensions': lib.RenderingServiceExtensions.values,
    'ResizeImagePolicy': lib.ResizeImagePolicy.values,
    'ScrollDirection': lib.ScrollDirection.values,
    'SelectionEventType': lib.SelectionEventType.values,
    'SelectionExtendDirection': lib.SelectionExtendDirection.values,
    'SelectionResult': lib.SelectionResult.values,
    'SelectionStatus': lib.SelectionStatus.values,
    'StackFit': lib.StackFit.values,
    'StrokeCap': lib.StrokeCap.values,
    'StrokeJoin': lib.StrokeJoin.values,
    'TableCellVerticalAlignment': lib.TableCellVerticalAlignment.values,
    'TextAffinity': lib.TextAffinity.values,
    'TextAlign': lib.TextAlign.values,
    'TextBaseline': lib.TextBaseline.values,
    'TextDecorationStyle': lib.TextDecorationStyle.values,
    'TextDirection': lib.TextDirection.values,
    'TextGranularity': lib.TextGranularity.values,
    'TextLeadingDistribution': lib.TextLeadingDistribution.values,
    'TextOverflow': lib.TextOverflow.values,
    'TextSelectionHandleType': lib.TextSelectionHandleType.values,
    'TextWidthBasis': lib.TextWidthBasis.values,
    'TileMode': lib.TileMode.values,
    'VertexMode': lib.VertexMode.values,
    'VerticalDirection': lib.VerticalDirection.values,
    'WrapAlignment': lib.WrapAlignment.values,
    'WrapCrossAlignment': lib.WrapCrossAlignment.values,
  };
 
  @override
  final Map<String, Map<String, Object? Function()>> statics = {
    'Alignment': {
      'bottomCenter': () => lib.Alignment.bottomCenter,
      'bottomLeft': () => lib.Alignment.bottomLeft,
      'bottomRight': () => lib.Alignment.bottomRight,
      'center': () => lib.Alignment.center,
      'centerLeft': () => lib.Alignment.centerLeft,
      'centerRight': () => lib.Alignment.centerRight,
      'topCenter': () => lib.Alignment.topCenter,
      'topLeft': () => lib.Alignment.topLeft,
      'topRight': () => lib.Alignment.topRight,
    },
    'AlignmentDirectional': {
      'bottomCenter': () => lib.AlignmentDirectional.bottomCenter,
      'bottomEnd': () => lib.AlignmentDirectional.bottomEnd,
      'bottomStart': () => lib.AlignmentDirectional.bottomStart,
      'center': () => lib.AlignmentDirectional.center,
      'centerEnd': () => lib.AlignmentDirectional.centerEnd,
      'centerStart': () => lib.AlignmentDirectional.centerStart,
      'topCenter': () => lib.AlignmentDirectional.topCenter,
      'topEnd': () => lib.AlignmentDirectional.topEnd,
      'topStart': () => lib.AlignmentDirectional.topStart,
    },
    'BorderRadius': {
      'zero': () => lib.BorderRadius.zero,
    },
    'BorderRadiusDirectional': {
      'zero': () => lib.BorderRadiusDirectional.zero,
    },
    'BorderSide': {
      'none': () => lib.BorderSide.none,
      'strokeAlignCenter': () => lib.BorderSide.strokeAlignCenter,
      'strokeAlignInside': () => lib.BorderSide.strokeAlignInside,
      'strokeAlignOutside': () => lib.BorderSide.strokeAlignOutside,
    },
    'EdgeInsets': {
      'zero': () => lib.EdgeInsets.zero,
    },
    'EdgeInsetsDirectional': {
      'zero': () => lib.EdgeInsetsDirectional.zero,
    },
    'EdgeInsetsGeometry': {
      'infinity': () => lib.EdgeInsetsGeometry.infinity,
    },
    'FontWeight': {
      'bold': () => lib.FontWeight.bold,
      'normal': () => lib.FontWeight.normal,
      'values': () => lib.FontWeight.values,
      'w100': () => lib.FontWeight.w100,
      'w200': () => lib.FontWeight.w200,
      'w300': () => lib.FontWeight.w300,
      'w400': () => lib.FontWeight.w400,
      'w500': () => lib.FontWeight.w500,
      'w600': () => lib.FontWeight.w600,
      'w700': () => lib.FontWeight.w700,
      'w800': () => lib.FontWeight.w800,
      'w900': () => lib.FontWeight.w900,
    },
    'FractionalOffset': {
      'bottomCenter': () => lib.FractionalOffset.bottomCenter,
      'bottomLeft': () => lib.FractionalOffset.bottomLeft,
      'bottomRight': () => lib.FractionalOffset.bottomRight,
      'center': () => lib.FractionalOffset.center,
      'centerLeft': () => lib.FractionalOffset.centerLeft,
      'centerRight': () => lib.FractionalOffset.centerRight,
      'topCenter': () => lib.FractionalOffset.topCenter,
      'topLeft': () => lib.FractionalOffset.topLeft,
      'topRight': () => lib.FractionalOffset.topRight,
    },
    'ImageConfiguration': {
      'empty': () => lib.ImageConfiguration.empty,
    },
    'InlineSpanSemanticsInformation': {
      'placeholder': () => lib.InlineSpanSemanticsInformation.placeholder,
    },
    'LinearBorder': {
      'none': () => lib.LinearBorder.none,
    },
    'MouseCursor': {
      'defer': () => lib.MouseCursor.defer,
      'uncontrolled': () => lib.MouseCursor.uncontrolled,
    },
    'Offset': {
      'infinite': () => lib.Offset.infinite,
      'zero': () => lib.Offset.zero,
    },
    'PlaceholderDimensions': {
      'empty': () => lib.PlaceholderDimensions.empty,
    },
    'PlaceholderSpan': {
      'placeholderCodeUnit': () => lib.PlaceholderSpan.placeholderCodeUnit,
    },
    'Radius': {
      'zero': () => lib.Radius.zero,
    },
    'Rect': {
      'largest': () => lib.Rect.largest,
      'zero': () => lib.Rect.zero,
    },
    'RelativeRect': {
      'fill': () => lib.RelativeRect.fill,
    },
    'RenderAbstractViewport': {
      'defaultCacheExtent': () => lib.RenderAbstractViewport.defaultCacheExtent,
    },
    'RenderErrorBox': {
      'backgroundColor': () => lib.RenderErrorBox.backgroundColor,
      'minimumWidth': () => lib.RenderErrorBox.minimumWidth,
      'padding': () => lib.RenderErrorBox.padding,
      'paragraphStyle': () => lib.RenderErrorBox.paragraphStyle,
      'textStyle': () => lib.RenderErrorBox.textStyle,
    },
    'RenderListWheelViewport': {
      'clipBehaviorAndRenderChildrenOutsideViewportConflict': () => lib.RenderListWheelViewport.clipBehaviorAndRenderChildrenOutsideViewportConflict,
      'defaultDiameterRatio': () => lib.RenderListWheelViewport.defaultDiameterRatio,
      'defaultPerspective': () => lib.RenderListWheelViewport.defaultPerspective,
      'diameterRatioZeroMessage': () => lib.RenderListWheelViewport.diameterRatioZeroMessage,
      'perspectiveTooHighMessage': () => lib.RenderListWheelViewport.perspectiveTooHighMessage,
    },
    'RenderObject': {
      'debugActiveLayout': () => lib.RenderObject.debugActiveLayout,
      'debugActivePaint': () => lib.RenderObject.debugActivePaint,
      'debugCheckingIntrinsics': () => lib.RenderObject.debugCheckingIntrinsics,
    },
    'RenderViewport': {
      'excludeFromScrolling': () => lib.RenderViewport.excludeFromScrolling,
      'useTwoPaneSemantics': () => lib.RenderViewport.useTwoPaneSemantics,
    },
    'RRect': {
      'zero': () => lib.RRect.zero,
    },
    'SemanticsAction': {
      'copy': () => lib.SemanticsAction.copy,
      'customAction': () => lib.SemanticsAction.customAction,
      'cut': () => lib.SemanticsAction.cut,
      'decrease': () => lib.SemanticsAction.decrease,
      'didGainAccessibilityFocus': () => lib.SemanticsAction.didGainAccessibilityFocus,
      'didLoseAccessibilityFocus': () => lib.SemanticsAction.didLoseAccessibilityFocus,
      'dismiss': () => lib.SemanticsAction.dismiss,
      'focus': () => lib.SemanticsAction.focus,
      'increase': () => lib.SemanticsAction.increase,
      'longPress': () => lib.SemanticsAction.longPress,
      'moveCursorBackwardByCharacter': () => lib.SemanticsAction.moveCursorBackwardByCharacter,
      'moveCursorBackwardByWord': () => lib.SemanticsAction.moveCursorBackwardByWord,
      'moveCursorForwardByCharacter': () => lib.SemanticsAction.moveCursorForwardByCharacter,
      'moveCursorForwardByWord': () => lib.SemanticsAction.moveCursorForwardByWord,
      'paste': () => lib.SemanticsAction.paste,
      'scrollDown': () => lib.SemanticsAction.scrollDown,
      'scrollLeft': () => lib.SemanticsAction.scrollLeft,
      'scrollRight': () => lib.SemanticsAction.scrollRight,
      'scrollUp': () => lib.SemanticsAction.scrollUp,
      'setSelection': () => lib.SemanticsAction.setSelection,
      'setText': () => lib.SemanticsAction.setText,
      'showOnScreen': () => lib.SemanticsAction.showOnScreen,
      'tap': () => lib.SemanticsAction.tap,
      'values': () => lib.SemanticsAction.values,
    },
    'SemanticsFlag': {
      'hasCheckedState': () => lib.SemanticsFlag.hasCheckedState,
      'hasEnabledState': () => lib.SemanticsFlag.hasEnabledState,
      'hasExpandedState': () => lib.SemanticsFlag.hasExpandedState,
      'hasImplicitScrolling': () => lib.SemanticsFlag.hasImplicitScrolling,
      'hasToggledState': () => lib.SemanticsFlag.hasToggledState,
      'isButton': () => lib.SemanticsFlag.isButton,
      'isChecked': () => lib.SemanticsFlag.isChecked,
      'isCheckStateMixed': () => lib.SemanticsFlag.isCheckStateMixed,
      'isEnabled': () => lib.SemanticsFlag.isEnabled,
      'isExpanded': () => lib.SemanticsFlag.isExpanded,
      'isFocusable': () => lib.SemanticsFlag.isFocusable,
      'isFocused': () => lib.SemanticsFlag.isFocused,
      'isHeader': () => lib.SemanticsFlag.isHeader,
      'isHidden': () => lib.SemanticsFlag.isHidden,
      'isImage': () => lib.SemanticsFlag.isImage,
      'isInMutuallyExclusiveGroup': () => lib.SemanticsFlag.isInMutuallyExclusiveGroup,
      'isKeyboardKey': () => lib.SemanticsFlag.isKeyboardKey,
      'isLink': () => lib.SemanticsFlag.isLink,
      'isLiveRegion': () => lib.SemanticsFlag.isLiveRegion,
      'isMultiline': () => lib.SemanticsFlag.isMultiline,
      'isObscured': () => lib.SemanticsFlag.isObscured,
      'isReadOnly': () => lib.SemanticsFlag.isReadOnly,
      'isSelected': () => lib.SemanticsFlag.isSelected,
      'isSlider': () => lib.SemanticsFlag.isSlider,
      'isTextField': () => lib.SemanticsFlag.isTextField,
      'isToggled': () => lib.SemanticsFlag.isToggled,
      'namesRoute': () => lib.SemanticsFlag.namesRoute,
      'scopesRoute': () => lib.SemanticsFlag.scopesRoute,
      'values': () => lib.SemanticsFlag.values,
    },
    'Size': {
      'infinite': () => lib.Size.infinite,
      'zero': () => lib.Size.zero,
    },
    'SliverGeometry': {
      'zero': () => lib.SliverGeometry.zero,
    },
    'StrutStyle': {
      'disabled': () => lib.StrutStyle.disabled,
    },
    'SystemMouseCursors': {
      'alias': () => lib.SystemMouseCursors.alias,
      'allScroll': () => lib.SystemMouseCursors.allScroll,
      'basic': () => lib.SystemMouseCursors.basic,
      'cell': () => lib.SystemMouseCursors.cell,
      'click': () => lib.SystemMouseCursors.click,
      'contextMenu': () => lib.SystemMouseCursors.contextMenu,
      'copy': () => lib.SystemMouseCursors.copy,
      'disappearing': () => lib.SystemMouseCursors.disappearing,
      'forbidden': () => lib.SystemMouseCursors.forbidden,
      'grab': () => lib.SystemMouseCursors.grab,
      'grabbing': () => lib.SystemMouseCursors.grabbing,
      'help': () => lib.SystemMouseCursors.help,
      'move': () => lib.SystemMouseCursors.move,
      'noDrop': () => lib.SystemMouseCursors.noDrop,
      'none': () => lib.SystemMouseCursors.none,
      'precise': () => lib.SystemMouseCursors.precise,
      'progress': () => lib.SystemMouseCursors.progress,
      'resizeColumn': () => lib.SystemMouseCursors.resizeColumn,
      'resizeDown': () => lib.SystemMouseCursors.resizeDown,
      'resizeDownLeft': () => lib.SystemMouseCursors.resizeDownLeft,
      'resizeDownRight': () => lib.SystemMouseCursors.resizeDownRight,
      'resizeLeft': () => lib.SystemMouseCursors.resizeLeft,
      'resizeLeftRight': () => lib.SystemMouseCursors.resizeLeftRight,
      'resizeRight': () => lib.SystemMouseCursors.resizeRight,
      'resizeRow': () => lib.SystemMouseCursors.resizeRow,
      'resizeUp': () => lib.SystemMouseCursors.resizeUp,
      'resizeUpDown': () => lib.SystemMouseCursors.resizeUpDown,
      'resizeUpLeft': () => lib.SystemMouseCursors.resizeUpLeft,
      'resizeUpLeftDownRight': () => lib.SystemMouseCursors.resizeUpLeftDownRight,
      'resizeUpRight': () => lib.SystemMouseCursors.resizeUpRight,
      'resizeUpRightDownLeft': () => lib.SystemMouseCursors.resizeUpRightDownLeft,
      'text': () => lib.SystemMouseCursors.text,
      'verticalText': () => lib.SystemMouseCursors.verticalText,
      'wait': () => lib.SystemMouseCursors.wait,
      'zoomIn': () => lib.SystemMouseCursors.zoomIn,
      'zoomOut': () => lib.SystemMouseCursors.zoomOut,
    },
    'TextAlignVertical': {
      'bottom': () => lib.TextAlignVertical.bottom,
      'center': () => lib.TextAlignVertical.center,
      'top': () => lib.TextAlignVertical.top,
    },
    'TextDecoration': {
      'lineThrough': () => lib.TextDecoration.lineThrough,
      'none': () => lib.TextDecoration.none,
      'overline': () => lib.TextDecoration.overline,
      'underline': () => lib.TextDecoration.underline,
    },
    'TextRange': {
      'empty': () => lib.TextRange.empty,
    },
    'TextScaler': {
      'noScaling': () => lib.TextScaler.noScaling,
    },
    'TreeSliverIndentationType': {
      'none': () => lib.TreeSliverIndentationType.none,
      'standard': () => lib.TreeSliverIndentationType.standard,
    },
  };
}
