import 'package:flutter/widgets.dart' as lib;

import '../library.dart';

class WidgetsLibrary extends FlutterLibrary {
  @override
  String get name => 'widgets';

  @override
  final List<String> widgets = [
    'AbsorbPointer',
    'ActionListener',
    'Actions',
    'Align',
    'AlignTransition',
    'AndroidView',
    'AndroidViewSurface',
    'AnimatedAlign',
    'AnimatedBuilder',
    'AnimatedContainer',
    'AnimatedCrossFade',
    'AnimatedDefaultTextStyle',
    'AnimatedFractionallySizedBox',
    'AnimatedGrid',
    'AnimatedList',
    'AnimatedList.separated',
    'AnimatedModalBarrier',
    'AnimatedOpacity',
    'AnimatedPadding',
    'AnimatedPhysicalModel',
    'AnimatedPositioned',
    'AnimatedPositioned.fromRect',
    'AnimatedPositionedDirectional',
    'AnimatedRotation',
    'AnimatedScale',
    'AnimatedSize',
    'AnimatedSlide',
    'AnimatedSwitcher',
    'AnnotatedRegion',
    'AppKitView',
    'AspectRatio',
    'AutocompleteHighlightedOption',
    'AutofillGroup',
    'AutomaticKeepAlive',
    'BackButtonListener',
    'BackdropFilter',
    'Banner',
    'Baseline',
    'BlockSemantics',
    'Builder',
    'CallbackShortcuts',
    'Center',
    'CheckedModeBanner',
    'ClipOval',
    'ClipPath',
    'ClipRect',
    'ClipRRect',
    'ColoredBox',
    'ColorFiltered',
    'Column',
    'CompositedTransformFollower',
    'CompositedTransformTarget',
    'ConstrainedBox',
    'ConstraintsTransformBox',
    'Container',
    'CustomMultiChildLayout',
    'CustomPaint',
    'CustomScrollView',
    'CustomSingleChildLayout',
    'DecoratedBox',
    'DecoratedBoxTransition',
    'DecoratedSliver',
    'DefaultAssetBundle',
    'DefaultSelectionStyle',
    'DefaultSelectionStyle.fallback',
    'DefaultTextEditingShortcuts',
    'DefaultTextHeightBehavior',
    'DefaultTextStyle',
    'DefaultTextStyle.fallback',
    'DefaultTextStyleTransition',
    'Directionality',
    'Dismissible',
    'DisplayFeatureSubScreen',
    'Draggable',
    'DraggableScrollableActuator',
    'DraggableScrollableSheet',
    'DragTarget',
    'DualTransitionBuilder',
    'EditableText',
    'ErrorWidget',
    'ErrorWidget.withDetails',
    'ExcludeFocus',
    'ExcludeFocusTraversal',
    'ExcludeSemantics',
    'Expanded',
    'FadeInImage',
    'FadeInImage.assetNetwork',
    'FadeInImage.memoryNetwork',
    'FadeTransition',
    'FittedBox',
    'Flex',
    'Flexible',
    'Flow',
    'Flow.unwrapped',
    'Focus',
    'Focus.withExternalFocusNode',
    'FocusableActionDetector',
    'FocusScope',
    'FocusScope.withExternalFocusNode',
    'FocusTraversalGroup',
    'FocusTraversalOrder',
    'Form',
    'FormField',
    'FractionallySizedBox',
    'FractionalTranslation',
    'FutureBuilder',
    'GestureDetector',
    'GlowingOverscrollIndicator',
    'GridPaper',
    'GridView',
    'GridView.builder',
    'GridView.count',
    'GridView.custom',
    'GridView.extent',
    'Hero',
    'HeroControllerScope',
    'HeroControllerScope.none',
    'HeroMode',
    'HtmlElementView',
    'HtmlElementView.fromTagName',
    'Icon',
    'IconTheme',
    'IgnoreBaseline',
    'IgnorePointer',
    'Image',
    'Image.asset',
    'Image.file',
    'Image.memory',
    'Image.network',
    'ImageFiltered',
    'ImageIcon',
    'IndexedSemantics',
    'IndexedStack',
    'InteractiveViewer',
    'InteractiveViewer.builder',
    'IntrinsicHeight',
    'IntrinsicWidth',
    'KeepAlive',
    'KeyboardListener',
    'KeyedSubtree',
    'KeyedSubtree.wrap',
    'LayoutBuilder',
    'LayoutId',
    'LimitedBox',
    'ListBody',
    'ListenableBuilder',
    'Listener',
    'ListView',
    'ListView.builder',
    'ListView.custom',
    'ListView.separated',
    'ListWheelScrollView',
    'ListWheelScrollView.useDelegate',
    'ListWheelViewport',
    'Localizations',
    'Localizations.override',
    'LongPressDraggable',
    'LookupBoundary',
    'MatrixTransition',
    'MediaQuery',
    'MediaQuery.removePadding',
    'MediaQuery.removeViewInsets',
    'MediaQuery.removeViewPadding',
    'MergeSemantics',
    'MetaData',
    'ModalBarrier',
    'MouseRegion',
    'NavigationToolbar',
    'Navigator',
    'NavigatorPopHandler',
    'NestedScrollView',
    'NestedScrollViewViewport',
    'NotificationListener',
    'Offstage',
    'Opacity',
    'OrientationBuilder',
    'OverflowBar',
    'OverflowBox',
    'Overlay',
    'OverlayPortal',
    'OverlayPortal.targetsRootOverlay',
    'Padding',
    'PageStorage',
    'PageView',
    'PageView.builder',
    'PageView.custom',
    'PerformanceOverlay',
    'PerformanceOverlay.allEnabled',
    'PhysicalModel',
    'PhysicalShape',
    'PinnedHeaderSliver',
    'Placeholder',
    'PlatformMenuBar',
    'PlatformSelectableRegionContextMenu',
    'PlatformViewLink',
    'PlatformViewSurface',
    'PopScope',
    'Positioned',
    'Positioned.directional',
    'Positioned.fill',
    'Positioned.fromRect',
    'Positioned.fromRelativeRect',
    'PositionedDirectional',
    'PositionedTransition',
    'PreferredSize',
    'PrimaryScrollController',
    'PrimaryScrollController.none',
    'RawAutocomplete',
    'RawGestureDetector',
    'RawImage',
    'RawKeyboardListener',
    'RawMagnifier',
    'RawScrollbar',
    'RawView',
    'RelativePositionedTransition',
    'RenderObjectToWidgetAdapter',
    'ReorderableDelayedDragStartListener',
    'ReorderableDragStartListener',
    'ReorderableList',
    'RepaintBoundary',
    'RepaintBoundary.wrap',
    'RestorationScope',
    'RichText',
    'RootRestorationScope',
    'RootWidget',
    'RotatedBox',
    'RotationTransition',
    'Router',
    'Router.withConfig',
    'Row',
    'SafeArea',
    'ScaleTransition',
    'Scrollable',
    'ScrollConfiguration',
    'ScrollNotificationObserver',
    'SelectableRegion',
    'SelectionContainer',
    'SelectionContainer.disabled',
    'SelectionRegistrarScope',
    'Semantics',
    'Semantics.fromProperties',
    'SemanticsDebugger',
    'ShaderMask',
    'SharedAppData',
    'ShortcutRegistrar',
    'Shortcuts',
    'Shortcuts.manager',
    'ShrinkWrappingViewport',
    'SingleChildScrollView',
    'SizeChangedLayoutNotifier',
    'SizedBox',
    'SizedBox.expand',
    'SizedBox.fromSize',
    'SizedBox.shrink',
    'SizedBox.square',
    'SizedOverflowBox',
    'SizeTransition',
    'SlideTransition',
    'SliverAnimatedGrid',
    'SliverAnimatedList',
    'SliverAnimatedOpacity',
    'SliverConstrainedCrossAxis',
    'SliverCrossAxisExpanded',
    'SliverCrossAxisGroup',
    'SliverFadeTransition',
    'SliverFillRemaining',
    'SliverFillViewport',
    'SliverFixedExtentList',
    'SliverFixedExtentList.builder',
    'SliverFixedExtentList.list',
    'SliverGrid',
    'SliverGrid.builder',
    'SliverGrid.count',
    'SliverGrid.extent',
    'SliverIgnorePointer',
    'SliverLayoutBuilder',
    'SliverList',
    'SliverList.builder',
    'SliverList.list',
    'SliverList.separated',
    'SliverMainAxisGroup',
    'SliverOffstage',
    'SliverOpacity',
    'SliverOverlapAbsorber',
    'SliverOverlapInjector',
    'SliverPadding',
    'SliverPersistentHeader',
    'SliverPrototypeExtentList',
    'SliverPrototypeExtentList.builder',
    'SliverPrototypeExtentList.list',
    'SliverReorderableList',
    'SliverResizingHeader',
    'SliverSafeArea',
    'SliverToBoxAdapter',
    'SliverVariedExtentList',
    'SliverVariedExtentList.builder',
    'SliverVariedExtentList.list',
    'SliverVisibility',
    'SliverVisibility.maintain',
    'SnapshotWidget',
    'Spacer',
    'Stack',
    'StatefulBuilder',
    'StreamBuilder',
    'StretchingOverscrollIndicator',
    'SystemContextMenu.editableText',
    'Table',
    'TableCell',
    'TapRegion',
    'TapRegionSurface',
    'Text',
    'Text.rich',
    'TextFieldTapRegion',
    'TextSelectionGestureDetector',
    'Texture',
    'TickerMode',
    'Title',
    'Transform',
    'Transform.flip',
    'Transform.rotate',
    'Transform.scale',
    'Transform.translate',
    'TreeSliver',
    'TweenAnimationBuilder',
    'TwoDimensionalScrollable',
    'UiKitView',
    'UnconstrainedBox',
    'UndoHistory',
    'UnmanagedRestorationScope',
    'ValueListenableBuilder',
    'View',
    'ViewAnchor',
    'ViewCollection',
    'Viewport',
    'Visibility',
    'Visibility.maintain',
    'WidgetInspector',
    'WidgetsApp',
    'WidgetsApp.router',
    'WidgetToRenderBoxAdapter',
    'WillPopScope',
    'Wrap',
  ];

  @override
  final Map<String, Function> classes = {
    'AbsorbPointer': lib.AbsorbPointer.new,
    'Accumulator': lib.Accumulator.new,
    'ActionDispatcher': lib.ActionDispatcher.new,
    'ActionListener': lib.ActionListener.new,
    'Actions': lib.Actions.new,
    'ActivateIntent': lib.ActivateIntent.new,
    'Align': lib.Align.new,
    'Alignment': lib.Alignment.new,
    'AlignmentDirectional': lib.AlignmentDirectional.new,
    'AlignmentGeometryTween': lib.AlignmentGeometryTween.new,
    'AlignmentTween': lib.AlignmentTween.new,
    'AlignTransition': lib.AlignTransition.new,
    'AlwaysScrollableScrollPhysics': lib.AlwaysScrollableScrollPhysics.new,
    'AlwaysStoppedAnimation': lib.AlwaysStoppedAnimation.new,
    'AndroidView': lib.AndroidView.new,
    'AndroidViewSurface': lib.AndroidViewSurface.new,
    'AnimatedAlign': lib.AnimatedAlign.new,
    'AnimatedBuilder': lib.AnimatedBuilder.new,
    'AnimatedContainer': lib.AnimatedContainer.new,
    'AnimatedCrossFade': lib.AnimatedCrossFade.new,
    'AnimatedDefaultTextStyle': lib.AnimatedDefaultTextStyle.new,
    'AnimatedFractionallySizedBox': lib.AnimatedFractionallySizedBox.new,
    'AnimatedGrid': lib.AnimatedGrid.new,
    'AnimatedGridState': lib.AnimatedGridState.new,
    'AnimatedList': lib.AnimatedList.new,
    'AnimatedList.separated': lib.AnimatedList.separated.call,
    'AnimatedListState': lib.AnimatedListState.new,
    'AnimatedModalBarrier': lib.AnimatedModalBarrier.new,
    'AnimatedOpacity': lib.AnimatedOpacity.new,
    'AnimatedPadding': lib.AnimatedPadding.new,
    'AnimatedPhysicalModel': lib.AnimatedPhysicalModel.new,
    'AnimatedPositioned': lib.AnimatedPositioned.new,
    'AnimatedPositioned.fromRect': lib.AnimatedPositioned.fromRect.call,
    'AnimatedPositionedDirectional': lib.AnimatedPositionedDirectional.new,
    'AnimatedRotation': lib.AnimatedRotation.new,
    'AnimatedScale': lib.AnimatedScale.new,
    'AnimatedSize': lib.AnimatedSize.new,
    'AnimatedSlide': lib.AnimatedSlide.new,
    'AnimatedSwitcher': lib.AnimatedSwitcher.new,
    'AnimationController': lib.AnimationController.new,
    'AnimationController.unbounded': lib.AnimationController.unbounded.call,
    'AnimationMax': lib.AnimationMax.new,
    'AnimationMean': lib.AnimationMean.new,
    'AnimationMin': lib.AnimationMin.new,
    'AnimationStyle': lib.AnimationStyle.new,
    'AnnotatedRegion': lib.AnnotatedRegion.new,
    'AppKitView': lib.AppKitView.new,
    'AppLifecycleListener': lib.AppLifecycleListener.new,
    'AspectRatio': lib.AspectRatio.new,
    'AssetBundleImageKey': lib.AssetBundleImageKey.new,
    'AssetImage': lib.AssetImage.new,
    'AsyncSnapshot.nothing': lib.AsyncSnapshot.nothing.call,
    'AsyncSnapshot.waiting': lib.AsyncSnapshot.waiting.call,
    'AsyncSnapshot.withData': lib.AsyncSnapshot.withData.call,
    'AsyncSnapshot.withError': lib.AsyncSnapshot.withError.call,
    'AutocompleteHighlightedOption': lib.AutocompleteHighlightedOption.new,
    'AutocompleteNextOptionIntent': lib.AutocompleteNextOptionIntent.new,
    'AutocompletePreviousOptionIntent': lib.AutocompletePreviousOptionIntent.new,
    'AutofillGroup': lib.AutofillGroup.new,
    'AutofillGroupState': lib.AutofillGroupState.new,
    'AutomaticKeepAlive': lib.AutomaticKeepAlive.new,
    'AutomaticNotchedShape': lib.AutomaticNotchedShape.new,
    'BackButtonListener': lib.BackButtonListener.new,
    'BackdropFilter': lib.BackdropFilter.new,
    'BallisticScrollActivity': lib.BallisticScrollActivity.new,
    'Banner': lib.Banner.new,
    'BannerPainter': lib.BannerPainter.new,
    'Baseline': lib.Baseline.new,
    'BeveledRectangleBorder': lib.BeveledRectangleBorder.new,
    'BlockSemantics': lib.BlockSemantics.new,
    'Border': lib.Border.new,
    'Border.all': lib.Border.all.call,
    'Border.fromBorderSide': lib.Border.fromBorderSide.call,
    'Border.symmetric': lib.Border.symmetric.call,
    'BorderDirectional': lib.BorderDirectional.new,
    'BorderRadius.all': lib.BorderRadius.all.call,
    'BorderRadius.circular': lib.BorderRadius.circular.call,
    'BorderRadius.horizontal': lib.BorderRadius.horizontal.call,
    'BorderRadius.only': lib.BorderRadius.only.call,
    'BorderRadius.vertical': lib.BorderRadius.vertical.call,
    'BorderRadiusDirectional.all': lib.BorderRadiusDirectional.all.call,
    'BorderRadiusDirectional.circular': lib.BorderRadiusDirectional.circular.call,
    'BorderRadiusDirectional.horizontal': lib.BorderRadiusDirectional.horizontal.call,
    'BorderRadiusDirectional.only': lib.BorderRadiusDirectional.only.call,
    'BorderRadiusDirectional.vertical': lib.BorderRadiusDirectional.vertical.call,
    'BorderRadiusTween': lib.BorderRadiusTween.new,
    'BorderSide': lib.BorderSide.new,
    'BorderTween': lib.BorderTween.new,
    'BottomNavigationBarItem': lib.BottomNavigationBarItem.new,
    'BouncingScrollPhysics': lib.BouncingScrollPhysics.new,
    'BouncingScrollSimulation': lib.BouncingScrollSimulation.new,
    'BoxConstraints': lib.BoxConstraints.new,
    'BoxConstraints.expand': lib.BoxConstraints.expand.call,
    'BoxConstraints.fromViewConstraints': lib.BoxConstraints.fromViewConstraints.call,
    'BoxConstraints.loose': lib.BoxConstraints.loose.call,
    'BoxConstraints.tight': lib.BoxConstraints.tight.call,
    'BoxConstraints.tightFor': lib.BoxConstraints.tightFor.call,
    'BoxConstraints.tightForFinite': lib.BoxConstraints.tightForFinite.call,
    'BoxConstraintsTween': lib.BoxConstraintsTween.new,
    'BoxDecoration': lib.BoxDecoration.new,
    'BoxShadow': lib.BoxShadow.new,
    'Builder': lib.Builder.new,
    'BuildOwner': lib.BuildOwner.new,
    'BuildScope': lib.BuildScope.new,
    'ButtonActivateIntent': lib.ButtonActivateIntent.new,
    'CallbackAction': lib.CallbackAction.new,
    'CallbackShortcuts': lib.CallbackShortcuts.new,
    'CatmullRomCurve': lib.CatmullRomCurve.new,
    'CatmullRomCurve.precompute': lib.CatmullRomCurve.precompute.call,
    'CatmullRomSpline': lib.CatmullRomSpline.new,
    'CatmullRomSpline.precompute': lib.CatmullRomSpline.precompute.call,
    'Center': lib.Center.new,
    'ChangeNotifier': lib.ChangeNotifier.new,
    'CharacterActivator': lib.CharacterActivator.new,
    'CheckedModeBanner': lib.CheckedModeBanner.new,
    'ChildBackButtonDispatcher': lib.ChildBackButtonDispatcher.new,
    'ChildVicinity': lib.ChildVicinity.new,
    'CircleBorder': lib.CircleBorder.new,
    'CircularNotchedRectangle': lib.CircularNotchedRectangle.new,
    'ClampingScrollPhysics': lib.ClampingScrollPhysics.new,
    'ClampingScrollSimulation': lib.ClampingScrollSimulation.new,
    'ClipboardStatusNotifier': lib.ClipboardStatusNotifier.new,
    'ClipOval': lib.ClipOval.new,
    'ClipPath': lib.ClipPath.new,
    'ClipRect': lib.ClipRect.new,
    'ClipRRect': lib.ClipRRect.new,
    'Color': lib.Color.new,
    'Color.fromARGB': lib.Color.fromARGB.call,
    'Color.fromRGBO': lib.Color.fromRGBO.call,
    'ColoredBox': lib.ColoredBox.new,
    'ColorFilter.linearToSrgbGamma': lib.ColorFilter.linearToSrgbGamma.call,
    'ColorFilter.matrix': lib.ColorFilter.matrix.call,
    'ColorFilter.mode': lib.ColorFilter.mode.call,
    'ColorFilter.srgbToLinearGamma': lib.ColorFilter.srgbToLinearGamma.call,
    'ColorFiltered': lib.ColorFiltered.new,
    'ColorProperty': lib.ColorProperty.new,
    'ColorSwatch': lib.ColorSwatch.new,
    'ColorTween': lib.ColorTween.new,
    'Column': lib.Column.new,
    'CompositedTransformFollower': lib.CompositedTransformFollower.new,
    'CompositedTransformTarget': lib.CompositedTransformTarget.new,
    'ConstantTween': lib.ConstantTween.new,
    'ConstrainedBox': lib.ConstrainedBox.new,
    'ConstraintsTransformBox': lib.ConstraintsTransformBox.new,
    'Container': lib.Container.new,
    'ContentInsertionConfiguration': lib.ContentInsertionConfiguration.new,
    'ContextMenuButtonItem': lib.ContextMenuButtonItem.new,
    'ContextMenuController': lib.ContextMenuController.new,
    'ContinuousRectangleBorder': lib.ContinuousRectangleBorder.new,
    'CopySelectionTextIntent.cut': lib.CopySelectionTextIntent.cut.call,
    'Cubic': lib.Cubic.new,
    'Curve2DSample': lib.Curve2DSample.new,
    'CurvedAnimation': lib.CurvedAnimation.new,
    'CurveTween': lib.CurveTween.new,
    'CustomMultiChildLayout': lib.CustomMultiChildLayout.new,
    'CustomPaint': lib.CustomPaint.new,
    'CustomPainterSemantics': lib.CustomPainterSemantics.new,
    'CustomScrollView': lib.CustomScrollView.new,
    'CustomSingleChildLayout': lib.CustomSingleChildLayout.new,
    'DebugCreator': lib.DebugCreator.new,
    'DecoratedBox': lib.DecoratedBox.new,
    'DecoratedBoxTransition': lib.DecoratedBoxTransition.new,
    'DecoratedSliver': lib.DecoratedSliver.new,
    'DecorationImage': lib.DecorationImage.new,
    'DecorationTween': lib.DecorationTween.new,
    'DefaultAssetBundle': lib.DefaultAssetBundle.new,
    'DefaultPlatformMenuDelegate': lib.DefaultPlatformMenuDelegate.new,
    'DefaultSelectionStyle': lib.DefaultSelectionStyle.new,
    'DefaultSelectionStyle.fallback': lib.DefaultSelectionStyle.fallback.call,
    'DefaultTextEditingShortcuts': lib.DefaultTextEditingShortcuts.new,
    'DefaultTextHeightBehavior': lib.DefaultTextHeightBehavior.new,
    'DefaultTextStyle': lib.DefaultTextStyle.new,
    'DefaultTextStyle.fallback': lib.DefaultTextStyle.fallback.call,
    'DefaultTextStyleTransition': lib.DefaultTextStyleTransition.new,
    'DefaultTransitionDelegate': lib.DefaultTransitionDelegate.new,
    'DefaultWidgetsLocalizations': lib.DefaultWidgetsLocalizations.new,
    'DeleteCharacterIntent': lib.DeleteCharacterIntent.new,
    'DeleteToLineBreakIntent': lib.DeleteToLineBreakIntent.new,
    'DeleteToNextWordBoundaryIntent': lib.DeleteToNextWordBoundaryIntent.new,
    'DesktopTextSelectionToolbarLayoutDelegate': lib.DesktopTextSelectionToolbarLayoutDelegate.new,
    'DevToolsDeepLinkProperty': lib.DevToolsDeepLinkProperty.new,
    'DirectionalFocusAction': lib.DirectionalFocusAction.new,
    'DirectionalFocusAction.forTextField': lib.DirectionalFocusAction.forTextField.call,
    'DirectionalFocusIntent': lib.DirectionalFocusIntent.new,
    'Directionality': lib.Directionality.new,
    'Dismissible': lib.Dismissible.new,
    'DismissIntent': lib.DismissIntent.new,
    'DismissUpdateDetails': lib.DismissUpdateDetails.new,
    'DisplayFeatureSubScreen': lib.DisplayFeatureSubScreen.new,
    'DisposableBuildContext': lib.DisposableBuildContext.new,
    'DoNothingAction': lib.DoNothingAction.new,
    'DoNothingAndStopPropagationIntent': lib.DoNothingAndStopPropagationIntent.new,
    'DoNothingAndStopPropagationTextIntent': lib.DoNothingAndStopPropagationTextIntent.new,
    'DoNothingIntent': lib.DoNothingIntent.new,
    'DragDownDetails': lib.DragDownDetails.new,
    'DragEndDetails': lib.DragEndDetails.new,
    'Draggable': lib.Draggable.new,
    'DraggableDetails': lib.DraggableDetails.new,
    'DraggableScrollableActuator': lib.DraggableScrollableActuator.new,
    'DraggableScrollableController': lib.DraggableScrollableController.new,
    'DraggableScrollableNotification': lib.DraggableScrollableNotification.new,
    'DraggableScrollableSheet': lib.DraggableScrollableSheet.new,
    'DragScrollActivity': lib.DragScrollActivity.new,
    'DragStartDetails': lib.DragStartDetails.new,
    'DragTarget': lib.DragTarget.new,
    'DragTargetDetails': lib.DragTargetDetails.new,
    'DragUpdateDetails': lib.DragUpdateDetails.new,
    'DrivenScrollActivity': lib.DrivenScrollActivity.new,
    'DualTransitionBuilder': lib.DualTransitionBuilder.new,
    'EdgeDraggingAutoScroller': lib.EdgeDraggingAutoScroller.new,
    'EdgeInsets.all': lib.EdgeInsets.all.call,
    'EdgeInsets.fromLTRB': lib.EdgeInsets.fromLTRB.call,
    'EdgeInsets.fromViewPadding': lib.EdgeInsets.fromViewPadding.call,
    'EdgeInsets.fromWindowPadding': lib.EdgeInsets.fromWindowPadding.call,
    'EdgeInsets.only': lib.EdgeInsets.only.call,
    'EdgeInsets.symmetric': lib.EdgeInsets.symmetric.call,
    'EdgeInsetsDirectional.all': lib.EdgeInsetsDirectional.all.call,
    'EdgeInsetsDirectional.fromSTEB': lib.EdgeInsetsDirectional.fromSTEB.call,
    'EdgeInsetsDirectional.only': lib.EdgeInsetsDirectional.only.call,
    'EdgeInsetsDirectional.symmetric': lib.EdgeInsetsDirectional.symmetric.call,
    'EdgeInsetsGeometryTween': lib.EdgeInsetsGeometryTween.new,
    'EdgeInsetsTween': lib.EdgeInsetsTween.new,
    'EditableText': lib.EditableText.new,
    'EditableTextState': lib.EditableTextState.new,
    'ElasticInCurve': lib.ElasticInCurve.new,
    'ElasticInOutCurve': lib.ElasticInOutCurve.new,
    'ElasticOutCurve': lib.ElasticOutCurve.new,
    'EmptyTextSelectionControls': lib.EmptyTextSelectionControls.new,
    'ErrorDescription': lib.ErrorDescription.new,
    'ErrorHint': lib.ErrorHint.new,
    'ErrorSummary': lib.ErrorSummary.new,
    'ErrorWidget': lib.ErrorWidget.new,
    'ErrorWidget.withDetails': lib.ErrorWidget.withDetails.call,
    'ExactAssetImage': lib.ExactAssetImage.new,
    'ExcludeFocus': lib.ExcludeFocus.new,
    'ExcludeFocusTraversal': lib.ExcludeFocusTraversal.new,
    'ExcludeSemantics': lib.ExcludeSemantics.new,
    'Expanded': lib.Expanded.new,
    'ExpandSelectionToDocumentBoundaryIntent': lib.ExpandSelectionToDocumentBoundaryIntent.new,
    'ExpandSelectionToLineBreakIntent': lib.ExpandSelectionToLineBreakIntent.new,
    'ExtendSelectionByCharacterIntent': lib.ExtendSelectionByCharacterIntent.new,
    'ExtendSelectionByPageIntent': lib.ExtendSelectionByPageIntent.new,
    'ExtendSelectionToDocumentBoundaryIntent': lib.ExtendSelectionToDocumentBoundaryIntent.new,
    'ExtendSelectionToLineBreakIntent': lib.ExtendSelectionToLineBreakIntent.new,
    'ExtendSelectionToNextParagraphBoundaryIntent': lib.ExtendSelectionToNextParagraphBoundaryIntent.new,
    'ExtendSelectionToNextParagraphBoundaryOrCaretLocationIntent': lib.ExtendSelectionToNextParagraphBoundaryOrCaretLocationIntent.new,
    'ExtendSelectionToNextWordBoundaryIntent': lib.ExtendSelectionToNextWordBoundaryIntent.new,
    'ExtendSelectionToNextWordBoundaryOrCaretLocationIntent': lib.ExtendSelectionToNextWordBoundaryOrCaretLocationIntent.new,
    'ExtendSelectionVerticallyToAdjacentLineIntent': lib.ExtendSelectionVerticallyToAdjacentLineIntent.new,
    'ExtendSelectionVerticallyToAdjacentPageIntent': lib.ExtendSelectionVerticallyToAdjacentPageIntent.new,
    'FadeInImage': lib.FadeInImage.new,
    'FadeInImage.assetNetwork': lib.FadeInImage.assetNetwork.call,
    'FadeInImage.memoryNetwork': lib.FadeInImage.memoryNetwork.call,
    'FadeTransition': lib.FadeTransition.new,
    'FileImage': lib.FileImage.new,
    'FittedBox': lib.FittedBox.new,
    'FittedSizes': lib.FittedSizes.new,
    'FixedColumnWidth': lib.FixedColumnWidth.new,
    'FixedExtentMetrics': lib.FixedExtentMetrics.new,
    'FixedExtentScrollController': lib.FixedExtentScrollController.new,
    'FixedExtentScrollPhysics': lib.FixedExtentScrollPhysics.new,
    'FixedScrollMetrics': lib.FixedScrollMetrics.new,
    'Flex': lib.Flex.new,
    'FlexColumnWidth': lib.FlexColumnWidth.new,
    'Flexible': lib.Flexible.new,
    'FlippedCurve': lib.FlippedCurve.new,
    'FlippedTweenSequence': lib.FlippedTweenSequence.new,
    'Flow': lib.Flow.new,
    'Flow.unwrapped': lib.Flow.unwrapped.call,
    'FlutterErrorDetails': lib.FlutterErrorDetails.new,
    'FlutterLogoDecoration': lib.FlutterLogoDecoration.new,
    'Focus': lib.Focus.new,
    'Focus.withExternalFocusNode': lib.Focus.withExternalFocusNode.call,
    'FocusableActionDetector': lib.FocusableActionDetector.new,
    'FocusManager': lib.FocusManager.new,
    'FocusNode': lib.FocusNode.new,
    'FocusScope': lib.FocusScope.new,
    'FocusScope.withExternalFocusNode': lib.FocusScope.withExternalFocusNode.call,
    'FocusScopeNode': lib.FocusScopeNode.new,
    'FocusTraversalGroup': lib.FocusTraversalGroup.new,
    'FocusTraversalOrder': lib.FocusTraversalOrder.new,
    'FontFeature': lib.FontFeature.new,
    'FontFeature.alternative': lib.FontFeature.alternative.call,
    'FontFeature.alternativeFractions': lib.FontFeature.alternativeFractions.call,
    'FontFeature.caseSensitiveForms': lib.FontFeature.caseSensitiveForms.call,
    'FontFeature.characterVariant': lib.FontFeature.characterVariant.call,
    'FontFeature.contextualAlternates': lib.FontFeature.contextualAlternates.call,
    'FontFeature.denominator': lib.FontFeature.denominator.call,
    'FontFeature.disable': lib.FontFeature.disable.call,
    'FontFeature.enable': lib.FontFeature.enable.call,
    'FontFeature.fractions': lib.FontFeature.fractions.call,
    'FontFeature.historicalForms': lib.FontFeature.historicalForms.call,
    'FontFeature.historicalLigatures': lib.FontFeature.historicalLigatures.call,
    'FontFeature.liningFigures': lib.FontFeature.liningFigures.call,
    'FontFeature.localeAware': lib.FontFeature.localeAware.call,
    'FontFeature.notationalForms': lib.FontFeature.notationalForms.call,
    'FontFeature.numerators': lib.FontFeature.numerators.call,
    'FontFeature.oldstyleFigures': lib.FontFeature.oldstyleFigures.call,
    'FontFeature.ordinalForms': lib.FontFeature.ordinalForms.call,
    'FontFeature.proportionalFigures': lib.FontFeature.proportionalFigures.call,
    'FontFeature.randomize': lib.FontFeature.randomize.call,
    'FontFeature.scientificInferiors': lib.FontFeature.scientificInferiors.call,
    'FontFeature.slashedZero': lib.FontFeature.slashedZero.call,
    'FontFeature.stylisticAlternates': lib.FontFeature.stylisticAlternates.call,
    'FontFeature.stylisticSet': lib.FontFeature.stylisticSet.call,
    'FontFeature.subscripts': lib.FontFeature.subscripts.call,
    'FontFeature.superscripts': lib.FontFeature.superscripts.call,
    'FontFeature.swash': lib.FontFeature.swash.call,
    'FontFeature.tabularFigures': lib.FontFeature.tabularFigures.call,
    'FontVariation': lib.FontVariation.new,
    'FontVariation.italic': lib.FontVariation.italic.call,
    'FontVariation.opticalSize': lib.FontVariation.opticalSize.call,
    'FontVariation.slant': lib.FontVariation.slant.call,
    'FontVariation.weight': lib.FontVariation.weight.call,
    'FontVariation.width': lib.FontVariation.width.call,
    'ForcePressDetails': lib.ForcePressDetails.new,
    'Form': lib.Form.new,
    'FormField': lib.FormField.new,
    'FormFieldState': lib.FormFieldState.new,
    'FormState': lib.FormState.new,
    'FractionallySizedBox': lib.FractionallySizedBox.new,
    'FractionalOffset': lib.FractionalOffset.new,
    'FractionalOffset.fromOffsetAndRect': lib.FractionalOffset.fromOffsetAndRect.call,
    'FractionalOffset.fromOffsetAndSize': lib.FractionalOffset.fromOffsetAndSize.call,
    'FractionalOffsetTween': lib.FractionalOffsetTween.new,
    'FractionalTranslation': lib.FractionalTranslation.new,
    'FractionColumnWidth': lib.FractionColumnWidth.new,
    'FutureBuilder': lib.FutureBuilder.new,
    'GestureDetector': lib.GestureDetector.new,
    'GestureRecognizerFactoryWithHandlers': lib.GestureRecognizerFactoryWithHandlers.new,
    'GlobalObjectKey': lib.GlobalObjectKey.new,
    'GlowingOverscrollIndicator': lib.GlowingOverscrollIndicator.new,
    'GlyphInfo': lib.GlyphInfo.new,
    'GradientRotation': lib.GradientRotation.new,
    'GridPaper': lib.GridPaper.new,
    'GridView': lib.GridView.new,
    'GridView.builder': lib.GridView.builder.call,
    'GridView.count': lib.GridView.count.call,
    'GridView.custom': lib.GridView.custom.call,
    'GridView.extent': lib.GridView.extent.call,
    'Hero': lib.Hero.new,
    'HeroController': lib.HeroController.new,
    'HeroControllerScope': lib.HeroControllerScope.new,
    'HeroControllerScope.none': lib.HeroControllerScope.none.call,
    'HeroMode': lib.HeroMode.new,
    'HoldScrollActivity': lib.HoldScrollActivity.new,
    'HSLColor.fromAHSL': lib.HSLColor.fromAHSL.call,
    'HSLColor.fromColor': lib.HSLColor.fromColor.call,
    'HSVColor.fromAHSV': lib.HSVColor.fromAHSV.call,
    'HSVColor.fromColor': lib.HSVColor.fromColor.call,
    'HtmlElementView': lib.HtmlElementView.new,
    'HtmlElementView.fromTagName': lib.HtmlElementView.fromTagName.call,
    'Icon': lib.Icon.new,
    'IconData': lib.IconData.new,
    'IconDataProperty': lib.IconDataProperty.new,
    'IconTheme': lib.IconTheme.new,
    'IconThemeData': lib.IconThemeData.new,
    'IconThemeData.fallback': lib.IconThemeData.fallback.call,
    'IdleScrollActivity': lib.IdleScrollActivity.new,
    'IgnoreBaseline': lib.IgnoreBaseline.new,
    'IgnorePointer': lib.IgnorePointer.new,
    'Image': lib.Image.new,
    'Image.asset': lib.Image.asset.call,
    'Image.file': lib.Image.file.call,
    'Image.memory': lib.Image.memory.call,
    'Image.network': lib.Image.network.call,
    'ImageCache': lib.ImageCache.new,
    'ImageChunkEvent': lib.ImageChunkEvent.new,
    'ImageConfiguration': lib.ImageConfiguration.new,
    'ImageFiltered': lib.ImageFiltered.new,
    'ImageIcon': lib.ImageIcon.new,
    'ImageInfo': lib.ImageInfo.new,
    'ImageShader': lib.ImageShader.new,
    'ImageSizeInfo': lib.ImageSizeInfo.new,
    'ImageStream': lib.ImageStream.new,
    'ImageStreamListener': lib.ImageStreamListener.new,
    'IndexedSemantics': lib.IndexedSemantics.new,
    'IndexedSlot': lib.IndexedSlot.new,
    'IndexedStack': lib.IndexedStack.new,
    'InheritedElement': lib.InheritedElement.new,
    'InheritedModelElement': lib.InheritedModelElement.new,
    'InlineSpanSemanticsInformation': lib.InlineSpanSemanticsInformation.new,
    'InspectorReferenceData': lib.InspectorReferenceData.new,
    'InspectorSelection': lib.InspectorSelection.new,
    'InspectorSerializationDelegate': lib.InspectorSerializationDelegate.new,
    'InteractiveViewer': lib.InteractiveViewer.new,
    'InteractiveViewer.builder': lib.InteractiveViewer.builder.call,
    'Interval': lib.Interval.new,
    'IntrinsicColumnWidth': lib.IntrinsicColumnWidth.new,
    'IntrinsicHeight': lib.IntrinsicHeight.new,
    'IntrinsicWidth': lib.IntrinsicWidth.new,
    'IntTween': lib.IntTween.new,
    'KeepAlive': lib.KeepAlive.new,
    'KeepAliveHandle': lib.KeepAliveHandle.new,
    'KeepAliveNotification': lib.KeepAliveNotification.new,
    'KeyboardInsertedContent': lib.KeyboardInsertedContent.new,
    'KeyboardInsertedContent.fromJson': lib.KeyboardInsertedContent.fromJson.call,
    'KeyboardListener': lib.KeyboardListener.new,
    'KeyedSubtree': lib.KeyedSubtree.new,
    'KeyedSubtree.wrap': lib.KeyedSubtree.wrap.call,
    'KeySet': lib.KeySet.new,
    'KeySet.fromSet': lib.KeySet.fromSet.call,
    'LabeledGlobalKey': lib.LabeledGlobalKey.new,
    'LayerLink': lib.LayerLink.new,
    'LayoutBuilder': lib.LayoutBuilder.new,
    'LayoutChangedNotification': lib.LayoutChangedNotification.new,
    'LayoutId': lib.LayoutId.new,
    'LeafRenderObjectElement': lib.LeafRenderObjectElement.new,
    'LexicalFocusOrder': lib.LexicalFocusOrder.new,
    'LimitedBox': lib.LimitedBox.new,
    'LinearBorder': lib.LinearBorder.new,
    'LinearBorder.bottom': lib.LinearBorder.bottom.call,
    'LinearBorder.end': lib.LinearBorder.end.call,
    'LinearBorder.start': lib.LinearBorder.start.call,
    'LinearBorder.top': lib.LinearBorder.top.call,
    'LinearBorderEdge': lib.LinearBorderEdge.new,
    'LinearGradient': lib.LinearGradient.new,
    'LineMetrics': lib.LineMetrics.new,
    'ListBody': lib.ListBody.new,
    'ListenableBuilder': lib.ListenableBuilder.new,
    'Listener': lib.Listener.new,
    'ListView': lib.ListView.new,
    'ListView.builder': lib.ListView.builder.call,
    'ListView.custom': lib.ListView.custom.call,
    'ListView.separated': lib.ListView.separated.call,
    'ListWheelChildBuilderDelegate': lib.ListWheelChildBuilderDelegate.new,
    'ListWheelChildListDelegate': lib.ListWheelChildListDelegate.new,
    'ListWheelChildLoopingListDelegate': lib.ListWheelChildLoopingListDelegate.new,
    'ListWheelElement': lib.ListWheelElement.new,
    'ListWheelScrollView': lib.ListWheelScrollView.new,
    'ListWheelScrollView.useDelegate': lib.ListWheelScrollView.useDelegate.call,
    'ListWheelViewport': lib.ListWheelViewport.new,
    'LiveTextInputStatusNotifier': lib.LiveTextInputStatusNotifier.new,
    'Locale': lib.Locale.new,
    'Locale.fromSubtags': lib.Locale.fromSubtags.call,
    'LocalHistoryEntry': lib.LocalHistoryEntry.new,
    'Localizations': lib.Localizations.new,
    'Localizations.override': lib.Localizations.override.call,
    'LogicalKeySet': lib.LogicalKeySet.new,
    'LogicalKeySet.fromSet': lib.LogicalKeySet.fromSet.call,
    'LongPressDraggable': lib.LongPressDraggable.new,
    'LongPressEndDetails': lib.LongPressEndDetails.new,
    'LongPressMoveUpdateDetails': lib.LongPressMoveUpdateDetails.new,
    'LongPressStartDetails': lib.LongPressStartDetails.new,
    'LookupBoundary': lib.LookupBoundary.new,
    'MagnifierController': lib.MagnifierController.new,
    'MagnifierDecoration': lib.MagnifierDecoration.new,
    'MagnifierInfo': lib.MagnifierInfo.new,
    'MaskFilter.blur': lib.MaskFilter.blur.call,
    'Matrix4': lib.Matrix4.new,
    'Matrix4.columns': lib.Matrix4.columns.call,
    'Matrix4.compose': lib.Matrix4.compose.call,
    'Matrix4.copy': lib.Matrix4.copy.call,
    'Matrix4.diagonal3': lib.Matrix4.diagonal3.call,
    'Matrix4.diagonal3Values': lib.Matrix4.diagonal3Values.call,
    'Matrix4.fromBuffer': lib.Matrix4.fromBuffer.call,
    'Matrix4.fromFloat64List': lib.Matrix4.fromFloat64List.call,
    'Matrix4.fromList': lib.Matrix4.fromList.call,
    'Matrix4.identity': lib.Matrix4.identity.call,
    'Matrix4.inverted': lib.Matrix4.inverted.call,
    'Matrix4.outer': lib.Matrix4.outer.call,
    'Matrix4.rotationX': lib.Matrix4.rotationX.call,
    'Matrix4.rotationY': lib.Matrix4.rotationY.call,
    'Matrix4.rotationZ': lib.Matrix4.rotationZ.call,
    'Matrix4.skew': lib.Matrix4.skew.call,
    'Matrix4.skewX': lib.Matrix4.skewX.call,
    'Matrix4.skewY': lib.Matrix4.skewY.call,
    'Matrix4.translation': lib.Matrix4.translation.call,
    'Matrix4.translationValues': lib.Matrix4.translationValues.call,
    'Matrix4.zero': lib.Matrix4.zero.call,
    'Matrix4Tween': lib.Matrix4Tween.new,
    'MatrixTransition': lib.MatrixTransition.new,
    'MaxColumnWidth': lib.MaxColumnWidth.new,
    'MediaQuery': lib.MediaQuery.new,
    'MediaQuery.removePadding': lib.MediaQuery.removePadding.call,
    'MediaQuery.removeViewInsets': lib.MediaQuery.removeViewInsets.call,
    'MediaQuery.removeViewPadding': lib.MediaQuery.removeViewPadding.call,
    'MediaQueryData': lib.MediaQueryData.new,
    'MediaQueryData.fromView': lib.MediaQueryData.fromView.call,
    'MediaQueryData.fromWindow': lib.MediaQueryData.fromWindow.call,
    'MemoryImage': lib.MemoryImage.new,
    'MergeSemantics': lib.MergeSemantics.new,
    'MetaData': lib.MetaData.new,
    'MinColumnWidth': lib.MinColumnWidth.new,
    'ModalBarrier': lib.ModalBarrier.new,
    'MouseRegion': lib.MouseRegion.new,
    'MultiChildRenderObjectElement': lib.MultiChildRenderObjectElement.new,
    'MultiFrameImageStreamCompleter': lib.MultiFrameImageStreamCompleter.new,
    'NavigationNotification': lib.NavigationNotification.new,
    'NavigationToolbar': lib.NavigationToolbar.new,
    'Navigator': lib.Navigator.new,
    'NavigatorObserver': lib.NavigatorObserver.new,
    'NavigatorPopHandler': lib.NavigatorPopHandler.new,
    'NavigatorState': lib.NavigatorState.new,
    'NestedScrollView': lib.NestedScrollView.new,
    'NestedScrollViewState': lib.NestedScrollViewState.new,
    'NestedScrollViewViewport': lib.NestedScrollViewViewport.new,
    'NeverScrollableScrollPhysics': lib.NeverScrollableScrollPhysics.new,
    'NextFocusAction': lib.NextFocusAction.new,
    'NextFocusIntent': lib.NextFocusIntent.new,
    'NotificationListener': lib.NotificationListener.new,
    'NumericFocusOrder': lib.NumericFocusOrder.new,
    'ObjectKey': lib.ObjectKey.new,
    'Offset': lib.Offset.new,
    'Offset.fromDirection': lib.Offset.fromDirection.call,
    'Offstage': lib.Offstage.new,
    'OneFrameImageStreamCompleter': lib.OneFrameImageStreamCompleter.new,
    'Opacity': lib.Opacity.new,
    'OrderedTraversalPolicy': lib.OrderedTraversalPolicy.new,
    'OrientationBuilder': lib.OrientationBuilder.new,
    'OvalBorder': lib.OvalBorder.new,
    'OverflowBar': lib.OverflowBar.new,
    'OverflowBox': lib.OverflowBox.new,
    'Overlay': lib.Overlay.new,
    'OverlayEntry': lib.OverlayEntry.new,
    'OverlayPortal': lib.OverlayPortal.new,
    'OverlayPortal.targetsRootOverlay': lib.OverlayPortal.targetsRootOverlay.call,
    'OverlayPortalController': lib.OverlayPortalController.new,
    'OverlayState': lib.OverlayState.new,
    'OverscrollIndicatorNotification': lib.OverscrollIndicatorNotification.new,
    'OverscrollNotification': lib.OverscrollNotification.new,
    'Padding': lib.Padding.new,
    'PageController': lib.PageController.new,
    'PageMetrics': lib.PageMetrics.new,
    'PageRouteBuilder': lib.PageRouteBuilder.new,
    'PageScrollPhysics': lib.PageScrollPhysics.new,
    'PageStorage': lib.PageStorage.new,
    'PageStorageBucket': lib.PageStorageBucket.new,
    'PageStorageKey': lib.PageStorageKey.new,
    'PageView': lib.PageView.new,
    'PageView.builder': lib.PageView.builder.call,
    'PageView.custom': lib.PageView.custom.call,
    'Paint': lib.Paint.new,
    'Paint.from': lib.Paint.from.call,
    'PaintingContext': lib.PaintingContext.new,
    'ParentDataElement': lib.ParentDataElement.new,
    'PasteTextIntent': lib.PasteTextIntent.new,
    'PerformanceOverlay': lib.PerformanceOverlay.new,
    'PerformanceOverlay.allEnabled': lib.PerformanceOverlay.allEnabled.call,
    'PhysicalModel': lib.PhysicalModel.new,
    'PhysicalShape': lib.PhysicalShape.new,
    'PinnedHeaderSliver': lib.PinnedHeaderSliver.new,
    'Placeholder': lib.Placeholder.new,
    'PlaceholderDimensions': lib.PlaceholderDimensions.new,
    'PlatformMenu': lib.PlatformMenu.new,
    'PlatformMenuBar': lib.PlatformMenuBar.new,
    'PlatformMenuItem': lib.PlatformMenuItem.new,
    'PlatformMenuItemGroup': lib.PlatformMenuItemGroup.new,
    'PlatformProvidedMenuItem': lib.PlatformProvidedMenuItem.new,
    'PlatformRouteInformationProvider': lib.PlatformRouteInformationProvider.new,
    'PlatformSelectableRegionContextMenu': lib.PlatformSelectableRegionContextMenu.new,
    'PlatformViewLink': lib.PlatformViewLink.new,
    'PlatformViewSurface': lib.PlatformViewSurface.new,
    'PointerCancelEvent': lib.PointerCancelEvent.new,
    'PointerDownEvent': lib.PointerDownEvent.new,
    'PointerMoveEvent': lib.PointerMoveEvent.new,
    'PointerUpEvent': lib.PointerUpEvent.new,
    'PopScope': lib.PopScope.new,
    'Positioned': lib.Positioned.new,
    'Positioned.directional': lib.Positioned.directional.call,
    'Positioned.fill': lib.Positioned.fill.call,
    'Positioned.fromRect': lib.Positioned.fromRect.call,
    'Positioned.fromRelativeRect': lib.Positioned.fromRelativeRect.call,
    'PositionedDirectional': lib.PositionedDirectional.new,
    'PositionedTransition': lib.PositionedTransition.new,
    'PreferredSize': lib.PreferredSize.new,
    'PreviousFocusAction': lib.PreviousFocusAction.new,
    'PreviousFocusIntent': lib.PreviousFocusIntent.new,
    'PrimaryScrollController': lib.PrimaryScrollController.new,
    'PrimaryScrollController.none': lib.PrimaryScrollController.none.call,
    'PrioritizedAction': lib.PrioritizedAction.new,
    'PrioritizedIntents': lib.PrioritizedIntents.new,
    'ProxyAnimation': lib.ProxyAnimation.new,
    'RadialGradient': lib.RadialGradient.new,
    'Radius.circular': lib.Radius.circular.call,
    'Radius.elliptical': lib.Radius.elliptical.call,
    'RangeMaintainingScrollPhysics': lib.RangeMaintainingScrollPhysics.new,
    'RawAutocomplete': lib.RawAutocomplete.new,
    'RawDialogRoute': lib.RawDialogRoute.new,
    'RawGestureDetector': lib.RawGestureDetector.new,
    'RawGestureDetectorState': lib.RawGestureDetectorState.new,
    'RawImage': lib.RawImage.new,
    'RawKeyboardListener': lib.RawKeyboardListener.new,
    'RawMagnifier': lib.RawMagnifier.new,
    'RawScrollbar': lib.RawScrollbar.new,
    'RawScrollbarState': lib.RawScrollbarState.new,
    'RawView': lib.RawView.new,
    'ReadingOrderTraversalPolicy': lib.ReadingOrderTraversalPolicy.new,
    'Rect.fromCenter': lib.Rect.fromCenter.call,
    'Rect.fromCircle': lib.Rect.fromCircle.call,
    'Rect.fromLTRB': lib.Rect.fromLTRB.call,
    'Rect.fromLTWH': lib.Rect.fromLTWH.call,
    'Rect.fromPoints': lib.Rect.fromPoints.call,
    'RectTween': lib.RectTween.new,
    'RedoTextIntent': lib.RedoTextIntent.new,
    'RelativePositionedTransition': lib.RelativePositionedTransition.new,
    'RelativeRect.fromDirectional': lib.RelativeRect.fromDirectional.call,
    'RelativeRect.fromLTRB': lib.RelativeRect.fromLTRB.call,
    'RelativeRect.fromRect': lib.RelativeRect.fromRect.call,
    'RelativeRect.fromSize': lib.RelativeRect.fromSize.call,
    'RelativeRectTween': lib.RelativeRectTween.new,
    'RenderNestedScrollViewViewport': lib.RenderNestedScrollViewViewport.new,
    'RenderObjectToWidgetAdapter': lib.RenderObjectToWidgetAdapter.new,
    'RenderObjectToWidgetElement': lib.RenderObjectToWidgetElement.new,
    'RenderSemanticsGestureHandler': lib.RenderSemanticsGestureHandler.new,
    'RenderSliverOverlapAbsorber': lib.RenderSliverOverlapAbsorber.new,
    'RenderSliverOverlapInjector': lib.RenderSliverOverlapInjector.new,
    'RenderTapRegion': lib.RenderTapRegion.new,
    'RenderTapRegionSurface': lib.RenderTapRegionSurface.new,
    'ReorderableDelayedDragStartListener': lib.ReorderableDelayedDragStartListener.new,
    'ReorderableDragStartListener': lib.ReorderableDragStartListener.new,
    'ReorderableList': lib.ReorderableList.new,
    'ReorderableListState': lib.ReorderableListState.new,
    'RepaintBoundary': lib.RepaintBoundary.new,
    'RepaintBoundary.wrap': lib.RepaintBoundary.wrap.call,
    'ReplaceTextIntent': lib.ReplaceTextIntent.new,
    'RequestFocusAction': lib.RequestFocusAction.new,
    'RequestFocusIntent': lib.RequestFocusIntent.new,
    'ResizeImage': lib.ResizeImage.new,
    'RestorableBool': lib.RestorableBool.new,
    'RestorableBoolN': lib.RestorableBoolN.new,
    'RestorableDateTime': lib.RestorableDateTime.new,
    'RestorableDateTimeN': lib.RestorableDateTimeN.new,
    'RestorableDouble': lib.RestorableDouble.new,
    'RestorableDoubleN': lib.RestorableDoubleN.new,
    'RestorableEnum': lib.RestorableEnum.new,
    'RestorableEnumN': lib.RestorableEnumN.new,
    'RestorableInt': lib.RestorableInt.new,
    'RestorableIntN': lib.RestorableIntN.new,
    'RestorableNum': lib.RestorableNum.new,
    'RestorableNumN': lib.RestorableNumN.new,
    'RestorableRouteFuture': lib.RestorableRouteFuture.new,
    'RestorableString': lib.RestorableString.new,
    'RestorableStringN': lib.RestorableStringN.new,
    'RestorableTextEditingController': lib.RestorableTextEditingController.new,
    'RestorableTextEditingController.fromValue': lib.RestorableTextEditingController.fromValue.call,
    'RestorationBucket.child': lib.RestorationBucket.child.call,
    'RestorationBucket.empty': lib.RestorationBucket.empty.call,
    'RestorationBucket.root': lib.RestorationBucket.root.call,
    'RestorationScope': lib.RestorationScope.new,
    'ReverseAnimation': lib.ReverseAnimation.new,
    'ReverseTween': lib.ReverseTween.new,
    'RichText': lib.RichText.new,
    'RootBackButtonDispatcher': lib.RootBackButtonDispatcher.new,
    'RootElement': lib.RootElement.new,
    'RootRestorationScope': lib.RootRestorationScope.new,
    'RootWidget': lib.RootWidget.new,
    'RotatedBox': lib.RotatedBox.new,
    'RotationTransition': lib.RotationTransition.new,
    'RoundedRectangleBorder': lib.RoundedRectangleBorder.new,
    'RouteInformation': lib.RouteInformation.new,
    'RouteObserver': lib.RouteObserver.new,
    'Router': lib.Router.new,
    'Router.withConfig': lib.Router.withConfig.call,
    'RouterConfig': lib.RouterConfig.new,
    'RouteSettings': lib.RouteSettings.new,
    'Row': lib.Row.new,
    'RRect.fromLTRBAndCorners': lib.RRect.fromLTRBAndCorners.call,
    'RRect.fromLTRBR': lib.RRect.fromLTRBR.call,
    'RRect.fromLTRBXY': lib.RRect.fromLTRBXY.call,
    'RRect.fromRectAndCorners': lib.RRect.fromRectAndCorners.call,
    'RRect.fromRectAndRadius': lib.RRect.fromRectAndRadius.call,
    'RRect.fromRectXY': lib.RRect.fromRectXY.call,
    'RSTransform': lib.RSTransform.new,
    'RSTransform.fromComponents': lib.RSTransform.fromComponents.call,
    'SafeArea': lib.SafeArea.new,
    'SawTooth': lib.SawTooth.new,
    'ScaleEndDetails': lib.ScaleEndDetails.new,
    'ScaleStartDetails': lib.ScaleStartDetails.new,
    'ScaleTransition': lib.ScaleTransition.new,
    'ScaleUpdateDetails': lib.ScaleUpdateDetails.new,
    'Scrollable': lib.Scrollable.new,
    'ScrollableDetails': lib.ScrollableDetails.new,
    'ScrollableDetails.horizontal': lib.ScrollableDetails.horizontal.call,
    'ScrollableDetails.vertical': lib.ScrollableDetails.vertical.call,
    'ScrollableState': lib.ScrollableState.new,
    'ScrollAction': lib.ScrollAction.new,
    'ScrollAwareImageProvider': lib.ScrollAwareImageProvider.new,
    'ScrollbarPainter': lib.ScrollbarPainter.new,
    'ScrollBehavior': lib.ScrollBehavior.new,
    'ScrollConfiguration': lib.ScrollConfiguration.new,
    'ScrollController': lib.ScrollController.new,
    'ScrollDragController': lib.ScrollDragController.new,
    'ScrollEndNotification': lib.ScrollEndNotification.new,
    'ScrollIncrementDetails': lib.ScrollIncrementDetails.new,
    'ScrollIntent': lib.ScrollIntent.new,
    'ScrollMetricsNotification': lib.ScrollMetricsNotification.new,
    'ScrollNotificationObserver': lib.ScrollNotificationObserver.new,
    'ScrollNotificationObserverState': lib.ScrollNotificationObserverState.new,
    'ScrollPhysics': lib.ScrollPhysics.new,
    'ScrollPositionWithSingleContext': lib.ScrollPositionWithSingleContext.new,
    'ScrollSpringSimulation': lib.ScrollSpringSimulation.new,
    'ScrollStartNotification': lib.ScrollStartNotification.new,
    'ScrollToDocumentBoundaryIntent': lib.ScrollToDocumentBoundaryIntent.new,
    'ScrollUpdateNotification': lib.ScrollUpdateNotification.new,
    'SelectableRegion': lib.SelectableRegion.new,
    'SelectableRegionState': lib.SelectableRegionState.new,
    'SelectAllTextIntent': lib.SelectAllTextIntent.new,
    'SelectIntent': lib.SelectIntent.new,
    'SelectionContainer': lib.SelectionContainer.new,
    'SelectionContainer.disabled': lib.SelectionContainer.disabled.call,
    'SelectionOverlay': lib.SelectionOverlay.new,
    'SelectionRegistrarScope': lib.SelectionRegistrarScope.new,
    'Semantics': lib.Semantics.new,
    'Semantics.fromProperties': lib.Semantics.fromProperties.call,
    'SemanticsDebugger': lib.SemanticsDebugger.new,
    'ShaderMask': lib.ShaderMask.new,
    'Shadow': lib.Shadow.new,
    'ShapeBorderClipper': lib.ShapeBorderClipper.new,
    'ShapeDecoration': lib.ShapeDecoration.new,
    'ShapeDecoration.fromBoxDecoration': lib.ShapeDecoration.fromBoxDecoration.call,
    'SharedAppData': lib.SharedAppData.new,
    'ShortcutManager': lib.ShortcutManager.new,
    'ShortcutMapProperty': lib.ShortcutMapProperty.new,
    'ShortcutRegistrar': lib.ShortcutRegistrar.new,
    'ShortcutRegistry': lib.ShortcutRegistry.new,
    'Shortcuts': lib.Shortcuts.new,
    'Shortcuts.manager': lib.Shortcuts.manager.call,
    'ShortcutSerialization.character': lib.ShortcutSerialization.character.call,
    'ShortcutSerialization.modifier': lib.ShortcutSerialization.modifier.call,
    'ShrinkWrappingViewport': lib.ShrinkWrappingViewport.new,
    'SingleActivator': lib.SingleActivator.new,
    'SingleChildRenderObjectElement': lib.SingleChildRenderObjectElement.new,
    'SingleChildScrollView': lib.SingleChildScrollView.new,
    'Size': lib.Size.new,
    'Size.copy': lib.Size.copy.call,
    'Size.fromHeight': lib.Size.fromHeight.call,
    'Size.fromRadius': lib.Size.fromRadius.call,
    'Size.fromWidth': lib.Size.fromWidth.call,
    'Size.square': lib.Size.square.call,
    'SizeChangedLayoutNotification': lib.SizeChangedLayoutNotification.new,
    'SizeChangedLayoutNotifier': lib.SizeChangedLayoutNotifier.new,
    'SizedBox': lib.SizedBox.new,
    'SizedBox.expand': lib.SizedBox.expand.call,
    'SizedBox.fromSize': lib.SizedBox.fromSize.call,
    'SizedBox.shrink': lib.SizedBox.shrink.call,
    'SizedBox.square': lib.SizedBox.square.call,
    'SizedOverflowBox': lib.SizedOverflowBox.new,
    'SizeTransition': lib.SizeTransition.new,
    'SizeTween': lib.SizeTween.new,
    'SlideTransition': lib.SlideTransition.new,
    'SliverAnimatedGrid': lib.SliverAnimatedGrid.new,
    'SliverAnimatedGridState': lib.SliverAnimatedGridState.new,
    'SliverAnimatedList': lib.SliverAnimatedList.new,
    'SliverAnimatedListState': lib.SliverAnimatedListState.new,
    'SliverAnimatedOpacity': lib.SliverAnimatedOpacity.new,
    'SliverChildBuilderDelegate': lib.SliverChildBuilderDelegate.new,
    'SliverChildListDelegate': lib.SliverChildListDelegate.new,
    'SliverChildListDelegate.fixed': lib.SliverChildListDelegate.fixed.call,
    'SliverConstrainedCrossAxis': lib.SliverConstrainedCrossAxis.new,
    'SliverCrossAxisExpanded': lib.SliverCrossAxisExpanded.new,
    'SliverCrossAxisGroup': lib.SliverCrossAxisGroup.new,
    'SliverFadeTransition': lib.SliverFadeTransition.new,
    'SliverFillRemaining': lib.SliverFillRemaining.new,
    'SliverFillViewport': lib.SliverFillViewport.new,
    'SliverFixedExtentList': lib.SliverFixedExtentList.new,
    'SliverFixedExtentList.builder': lib.SliverFixedExtentList.builder.call,
    'SliverFixedExtentList.list': lib.SliverFixedExtentList.list.call,
    'SliverGrid': lib.SliverGrid.new,
    'SliverGrid.builder': lib.SliverGrid.builder.call,
    'SliverGrid.count': lib.SliverGrid.count.call,
    'SliverGrid.extent': lib.SliverGrid.extent.call,
    'SliverGridDelegateWithFixedCrossAxisCount': lib.SliverGridDelegateWithFixedCrossAxisCount.new,
    'SliverGridDelegateWithMaxCrossAxisExtent': lib.SliverGridDelegateWithMaxCrossAxisExtent.new,
    'SliverIgnorePointer': lib.SliverIgnorePointer.new,
    'SliverLayoutBuilder': lib.SliverLayoutBuilder.new,
    'SliverList': lib.SliverList.new,
    'SliverList.builder': lib.SliverList.builder.call,
    'SliverList.list': lib.SliverList.list.call,
    'SliverList.separated': lib.SliverList.separated.call,
    'SliverMainAxisGroup': lib.SliverMainAxisGroup.new,
    'SliverMultiBoxAdaptorElement': lib.SliverMultiBoxAdaptorElement.new,
    'SliverOffstage': lib.SliverOffstage.new,
    'SliverOpacity': lib.SliverOpacity.new,
    'SliverOverlapAbsorber': lib.SliverOverlapAbsorber.new,
    'SliverOverlapAbsorberHandle': lib.SliverOverlapAbsorberHandle.new,
    'SliverOverlapInjector': lib.SliverOverlapInjector.new,
    'SliverPadding': lib.SliverPadding.new,
    'SliverPersistentHeader': lib.SliverPersistentHeader.new,
    'SliverPrototypeExtentList': lib.SliverPrototypeExtentList.new,
    'SliverPrototypeExtentList.builder': lib.SliverPrototypeExtentList.builder.call,
    'SliverPrototypeExtentList.list': lib.SliverPrototypeExtentList.list.call,
    'SliverReorderableList': lib.SliverReorderableList.new,
    'SliverReorderableListState': lib.SliverReorderableListState.new,
    'SliverResizingHeader': lib.SliverResizingHeader.new,
    'SliverSafeArea': lib.SliverSafeArea.new,
    'SliverToBoxAdapter': lib.SliverToBoxAdapter.new,
    'SliverVariedExtentList': lib.SliverVariedExtentList.new,
    'SliverVariedExtentList.builder': lib.SliverVariedExtentList.builder.call,
    'SliverVariedExtentList.list': lib.SliverVariedExtentList.list.call,
    'SliverVisibility': lib.SliverVisibility.new,
    'SliverVisibility.maintain': lib.SliverVisibility.maintain.call,
    'SlottedRenderObjectElement': lib.SlottedRenderObjectElement.new,
    'SnapshotController': lib.SnapshotController.new,
    'SnapshotWidget': lib.SnapshotWidget.new,
    'Spacer': lib.Spacer.new,
    'SpellCheckConfiguration': lib.SpellCheckConfiguration.new,
    'SpellCheckConfiguration.disabled': lib.SpellCheckConfiguration.disabled.call,
    'Split': lib.Split.new,
    'SpringDescription': lib.SpringDescription.new,
    'SpringDescription.withDampingRatio': lib.SpringDescription.withDampingRatio.call,
    'Stack': lib.Stack.new,
    'StadiumBorder': lib.StadiumBorder.new,
    'StarBorder': lib.StarBorder.new,
    'StarBorder.polygon': lib.StarBorder.polygon.call,
    'StatefulBuilder': lib.StatefulBuilder.new,
    'StatefulElement': lib.StatefulElement.new,
    'StatelessElement': lib.StatelessElement.new,
    'StepTween': lib.StepTween.new,
    'StreamBuilder': lib.StreamBuilder.new,
    'StretchingOverscrollIndicator': lib.StretchingOverscrollIndicator.new,
    'StrutStyle': lib.StrutStyle.new,
    'StrutStyle.fromTextStyle': lib.StrutStyle.fromTextStyle.call,
    'SweepGradient': lib.SweepGradient.new,
    'SystemContextMenu.editableText': lib.SystemContextMenu.editableText.call,
    'Table': lib.Table.new,
    'TableBorder': lib.TableBorder.new,
    'TableBorder.all': lib.TableBorder.all.call,
    'TableBorder.symmetric': lib.TableBorder.symmetric.call,
    'TableCell': lib.TableCell.new,
    'TableRow': lib.TableRow.new,
    'TapDownDetails': lib.TapDownDetails.new,
    'TapRegion': lib.TapRegion.new,
    'TapRegionSurface': lib.TapRegionSurface.new,
    'TapUpDetails': lib.TapUpDetails.new,
    'Text': lib.Text.new,
    'Text.rich': lib.Text.rich.call,
    'TextAlignVertical': lib.TextAlignVertical.new,
    'TextBox.fromLTRBD': lib.TextBox.fromLTRBD.call,
    'TextDecoration.combine': lib.TextDecoration.combine.call,
    'TextEditingController': lib.TextEditingController.new,
    'TextEditingController.fromValue': lib.TextEditingController.fromValue.call,
    'TextEditingValue': lib.TextEditingValue.new,
    'TextEditingValue.fromJSON': lib.TextEditingValue.fromJSON.call,
    'TextFieldTapRegion': lib.TextFieldTapRegion.new,
    'TextHeightBehavior': lib.TextHeightBehavior.new,
    'TextInputType.numberWithOptions': lib.TextInputType.numberWithOptions.call,
    'TextMagnifierConfiguration': lib.TextMagnifierConfiguration.new,
    'TextPainter': lib.TextPainter.new,
    'TextPosition': lib.TextPosition.new,
    'TextRange': lib.TextRange.new,
    'TextRange.collapsed': lib.TextRange.collapsed.call,
    'TextSelection': lib.TextSelection.new,
    'TextSelection.collapsed': lib.TextSelection.collapsed.call,
    'TextSelection.fromPosition': lib.TextSelection.fromPosition.call,
    'TextSelectionGestureDetector': lib.TextSelectionGestureDetector.new,
    'TextSelectionGestureDetectorBuilder': lib.TextSelectionGestureDetectorBuilder.new,
    'TextSelectionOverlay': lib.TextSelectionOverlay.new,
    'TextSelectionPoint': lib.TextSelectionPoint.new,
    'TextSelectionToolbarAnchors': lib.TextSelectionToolbarAnchors.new,
    'TextSelectionToolbarAnchors.fromSelection': lib.TextSelectionToolbarAnchors.fromSelection.call,
    'TextSelectionToolbarLayoutDelegate': lib.TextSelectionToolbarLayoutDelegate.new,
    'TextSpan': lib.TextSpan.new,
    'TextStyle': lib.TextStyle.new,
    'TextStyleTween': lib.TextStyleTween.new,
    'Texture': lib.Texture.new,
    'ThreePointCubic': lib.ThreePointCubic.new,
    'Threshold': lib.Threshold.new,
    'TickerFuture.complete': lib.TickerFuture.complete.call,
    'TickerMode': lib.TickerMode.new,
    'Title': lib.Title.new,
    'Tolerance': lib.Tolerance.new,
    'ToolbarItemsParentData': lib.ToolbarItemsParentData.new,
    'ToolbarOptions': lib.ToolbarOptions.new,
    'TrackingScrollController': lib.TrackingScrollController.new,
    'TrainHoppingAnimation': lib.TrainHoppingAnimation.new,
    'Transform': lib.Transform.new,
    'Transform.flip': lib.Transform.flip.call,
    'Transform.rotate': lib.Transform.rotate.call,
    'Transform.scale': lib.Transform.scale.call,
    'Transform.translate': lib.Transform.translate.call,
    'TransformationController': lib.TransformationController.new,
    'TransformProperty': lib.TransformProperty.new,
    'TransposeCharactersIntent': lib.TransposeCharactersIntent.new,
    'TreeSliver': lib.TreeSliver.new,
    'TreeSliverController': lib.TreeSliverController.new,
    'TreeSliverNode': lib.TreeSliverNode.new,
    'Tween': lib.Tween.new,
    'TweenAnimationBuilder': lib.TweenAnimationBuilder.new,
    'TweenSequence': lib.TweenSequence.new,
    'TweenSequenceItem': lib.TweenSequenceItem.new,
    'TwoDimensionalChildBuilderDelegate': lib.TwoDimensionalChildBuilderDelegate.new,
    'TwoDimensionalChildListDelegate': lib.TwoDimensionalChildListDelegate.new,
    'TwoDimensionalScrollable': lib.TwoDimensionalScrollable.new,
    'TwoDimensionalScrollableState': lib.TwoDimensionalScrollableState.new,
    'TwoDimensionalViewportParentData': lib.TwoDimensionalViewportParentData.new,
    'UiKitView': lib.UiKitView.new,
    'UnconstrainedBox': lib.UnconstrainedBox.new,
    'UndoHistory': lib.UndoHistory.new,
    'UndoHistoryController': lib.UndoHistoryController.new,
    'UndoHistoryState': lib.UndoHistoryState.new,
    'UndoHistoryValue': lib.UndoHistoryValue.new,
    'UndoTextIntent': lib.UndoTextIntent.new,
    'UniqueKey': lib.UniqueKey.new,
    'UnmanagedRestorationScope': lib.UnmanagedRestorationScope.new,
    'UpdateSelectionIntent': lib.UpdateSelectionIntent.new,
    'UserScrollNotification': lib.UserScrollNotification.new,
    'ValueKey': lib.ValueKey.new,
    'ValueListenableBuilder': lib.ValueListenableBuilder.new,
    'ValueNotifier': lib.ValueNotifier.new,
    'Velocity': lib.Velocity.new,
    'View': lib.View.new,
    'ViewAnchor': lib.ViewAnchor.new,
    'ViewCollection': lib.ViewCollection.new,
    'Viewport': lib.Viewport.new,
    'Visibility': lib.Visibility.new,
    'Visibility.maintain': lib.Visibility.maintain.call,
    'VoidCallbackAction': lib.VoidCallbackAction.new,
    'VoidCallbackIntent': lib.VoidCallbackIntent.new,
    'WeakMap': lib.WeakMap.new,
    'WidgetInspector': lib.WidgetInspector.new,
    'WidgetOrderTraversalPolicy': lib.WidgetOrderTraversalPolicy.new,
    'WidgetsApp': lib.WidgetsApp.new,
    'WidgetsApp.router': lib.WidgetsApp.router.call,
    'WidgetsFlutterBinding': lib.WidgetsFlutterBinding.new,
    'WidgetSpan': lib.WidgetSpan.new,
    'WidgetStatePropertyAll': lib.WidgetStatePropertyAll.new,
    'WidgetStatesController': lib.WidgetStatesController.new,
    'WidgetToRenderBoxAdapter': lib.WidgetToRenderBoxAdapter.new,
    'WillPopScope': lib.WillPopScope.new,
    'Wrap': lib.Wrap.new,
  };

  @override
  final Map<String, Function> functions = {
    'applyBoxFit': lib.applyBoxFit.call,
    'axisDirectionIsReversed': lib.axisDirectionIsReversed.call,
    'axisDirectionToAxis': lib.axisDirectionToAxis.call,
    'basicLocaleListResolution': lib.basicLocaleListResolution.call,
    'buildTextSpanWithSpellCheckSuggestions': lib.buildTextSpanWithSpellCheckSuggestions.call,
    'childDragAnchorStrategy': lib.childDragAnchorStrategy.call,
    'combineKeyEventResults': lib.combineKeyEventResults.call,
    'combineSemanticsInfo': lib.combineSemanticsInfo.call,
    'createLocalImageConfiguration': lib.createLocalImageConfiguration.call,
    'debugAssertAllPaintingVarsUnset': lib.debugAssertAllPaintingVarsUnset.call,
    'debugAssertAllWidgetVarsUnset': lib.debugAssertAllWidgetVarsUnset.call,
    'debugCheckHasDirectionality': lib.debugCheckHasDirectionality.call,
    'debugCheckHasMediaQuery': lib.debugCheckHasMediaQuery.call,
    'debugCheckHasOverlay': lib.debugCheckHasOverlay.call,
    'debugCheckHasTable': lib.debugCheckHasTable.call,
    'debugCheckHasWidgetsLocalizations': lib.debugCheckHasWidgetsLocalizations.call,
    'debugChildrenHaveDuplicateKeys': lib.debugChildrenHaveDuplicateKeys.call,
    'debugDescribeFocusTree': lib.debugDescribeFocusTree.call,
    'debugDescribeTransform': lib.debugDescribeTransform.call,
    'debugDumpApp': lib.debugDumpApp.call,
    'debugDumpFocusTree': lib.debugDumpFocusTree.call,
    'debugDumpLayerTree': lib.debugDumpLayerTree.call,
    'debugDumpRenderTree': lib.debugDumpRenderTree.call,
    'debugFlushLastFrameImageSizeInfo': lib.debugFlushLastFrameImageSizeInfo.call,
    'debugIsLocalCreationLocation': lib.debugIsLocalCreationLocation.call,
    'debugIsWidgetLocalCreation': lib.debugIsWidgetLocalCreation.call,
    'debugItemsHaveDuplicateKeys': lib.debugItemsHaveDuplicateKeys.call,
    'debugPrintStack': lib.debugPrintStack.call,
    'debugTransformDebugCreator': lib.debugTransformDebugCreator.call,
    'debugWidgetBuilderValue': lib.debugWidgetBuilderValue.call,
    'decodeImageFromList': lib.decodeImageFromList.call,
    'defaultScrollNotificationPredicate': lib.defaultScrollNotificationPredicate.call,
    'flipAxis': lib.flipAxis.call,
    'flipAxisDirection': lib.flipAxisDirection.call,
    'getAxisDirectionFromAxisReverseAndDirectionality': lib.getAxisDirectionFromAxisReverseAndDirectionality.call,
    'hashList': lib.hashList.call,
    'hashValues': lib.hashValues.call,
    'intentForMacOSSelector': lib.intentForMacOSSelector.call,
    'lerpFontVariations': lib.lerpFontVariations.call,
    'paintBorder': lib.paintBorder.call,
    'paintImage': lib.paintImage.call,
    'paintZigZag': lib.paintZigZag.call,
    'pointerDragAnchorStrategy': lib.pointerDragAnchorStrategy.call,
    'positionDependentBox': lib.positionDependentBox.call,
    'precacheImage': lib.precacheImage.call,
    'runApp': lib.runApp.call,
    'runWidget': lib.runWidget.call,
    'showGeneralDialog': lib.showGeneralDialog.call,
    'textDirectionToAxisDirection': lib.textDirectionToAxisDirection.call,
  };

  @override
  final Map<String, Object?> constants = {
    'factory': lib.factory,
    'immutable': lib.immutable,
    'kAlwaysCompleteAnimation': lib.kAlwaysCompleteAnimation,
    'kAlwaysDismissedAnimation': lib.kAlwaysDismissedAnimation,
    'kDefaultContentInsertionMimeTypes': lib.kDefaultContentInsertionMimeTypes,
    'kDefaultFontSize': lib.kDefaultFontSize,
    'kDefaultRouteTraversalEdgeBehavior': lib.kDefaultRouteTraversalEdgeBehavior,
    'kTextHeightNone': lib.kTextHeightNone,
    'mustCallSuper': lib.mustCallSuper,
    'optionalTypeArgs': lib.optionalTypeArgs,
    'protected': lib.protected,
    'required': lib.required,
    'staticIconProvider': lib.staticIconProvider,
    'visibleForTesting': lib.visibleForTesting,
    'widgetFactory': lib.widgetFactory,
  };

  @override
  final Map<String, List<Enum>> enums = {
    'AndroidOverscrollIndicator': lib.AndroidOverscrollIndicator.values,
    'AnimationBehavior': lib.AnimationBehavior.values,
    'AnimationStatus': lib.AnimationStatus.values,
    'AppLifecycleState': lib.AppLifecycleState.values,
    'AutofillContextAction': lib.AutofillContextAction.values,
    'AutovalidateMode': lib.AutovalidateMode.values,
    'Axis': lib.Axis.values,
    'AxisDirection': lib.AxisDirection.values,
    'BannerLocation': lib.BannerLocation.values,
    'BlendMode': lib.BlendMode.values,
    'BlurStyle': lib.BlurStyle.values,
    'BorderStyle': lib.BorderStyle.values,
    'BoxFit': lib.BoxFit.values,
    'BoxShape': lib.BoxShape.values,
    'Clip': lib.Clip.values,
    'ClipboardStatus': lib.ClipboardStatus.values,
    'ConnectionState': lib.ConnectionState.values,
    'ContextMenuButtonType': lib.ContextMenuButtonType.values,
    'CrossAxisAlignment': lib.CrossAxisAlignment.values,
    'CrossFadeState': lib.CrossFadeState.values,
    'DecorationPosition': lib.DecorationPosition.values,
    'DiagnosticLevel': lib.DiagnosticLevel.values,
    'DiagonalDragBehavior': lib.DiagonalDragBehavior.values,
    'DismissDirection': lib.DismissDirection.values,
    'FilterQuality': lib.FilterQuality.values,
    'FlexFit': lib.FlexFit.values,
    'FlutterLogoStyle': lib.FlutterLogoStyle.values,
    'FocusHighlightMode': lib.FocusHighlightMode.values,
    'FocusHighlightStrategy': lib.FocusHighlightStrategy.values,
    'FontStyle': lib.FontStyle.values,
    'GrowthDirection': lib.GrowthDirection.values,
    'HeroFlightDirection': lib.HeroFlightDirection.values,
    'HitTestBehavior': lib.HitTestBehavior.values,
    'ImageRepeat': lib.ImageRepeat.values,
    'KeyEventResult': lib.KeyEventResult.values,
    'LiveTextInputStatus': lib.LiveTextInputStatus.values,
    'LockState': lib.LockState.values,
    'MainAxisAlignment': lib.MainAxisAlignment.values,
    'MainAxisSize': lib.MainAxisSize.values,
    'NavigationMode': lib.NavigationMode.values,
    'OptionsViewOpenDirection': lib.OptionsViewOpenDirection.values,
    'Orientation': lib.Orientation.values,
    'OverflowBarAlignment': lib.OverflowBarAlignment.values,
    'PaintingStyle': lib.PaintingStyle.values,
    'PanAxis': lib.PanAxis.values,
    'PathFillType': lib.PathFillType.values,
    'PathOperation': lib.PathOperation.values,
    'PlaceholderAlignment': lib.PlaceholderAlignment.values,
    'PlatformProvidedMenuItemType': lib.PlatformProvidedMenuItemType.values,
    'RenderComparison': lib.RenderComparison.values,
    'ResizeImagePolicy': lib.ResizeImagePolicy.values,
    'RouteInformationReportingType': lib.RouteInformationReportingType.values,
    'RoutePopDisposition': lib.RoutePopDisposition.values,
    'ScrollbarOrientation': lib.ScrollbarOrientation.values,
    'ScrollDecelerationRate': lib.ScrollDecelerationRate.values,
    'ScrollIncrementType': lib.ScrollIncrementType.values,
    'ScrollPositionAlignmentPolicy': lib.ScrollPositionAlignmentPolicy.values,
    'ScrollViewKeyboardDismissBehavior': lib.ScrollViewKeyboardDismissBehavior.values,
    'SelectionChangedCause': lib.SelectionChangedCause.values,
    'SmartDashesType': lib.SmartDashesType.values,
    'SmartQuotesType': lib.SmartQuotesType.values,
    'SnapshotMode': lib.SnapshotMode.values,
    'StackFit': lib.StackFit.values,
    'StrokeCap': lib.StrokeCap.values,
    'StrokeJoin': lib.StrokeJoin.values,
    'TableCellVerticalAlignment': lib.TableCellVerticalAlignment.values,
    'TargetPlatform': lib.TargetPlatform.values,
    'TextAffinity': lib.TextAffinity.values,
    'TextAlign': lib.TextAlign.values,
    'TextBaseline': lib.TextBaseline.values,
    'TextDecorationStyle': lib.TextDecorationStyle.values,
    'TextDirection': lib.TextDirection.values,
    'TextLeadingDistribution': lib.TextLeadingDistribution.values,
    'TextOverflow': lib.TextOverflow.values,
    'TextSelectionHandleType': lib.TextSelectionHandleType.values,
    'TextWidthBasis': lib.TextWidthBasis.values,
    'TileMode': lib.TileMode.values,
    'TraversalDirection': lib.TraversalDirection.values,
    'TraversalEdgeBehavior': lib.TraversalEdgeBehavior.values,
    'UnfocusDisposition': lib.UnfocusDisposition.values,
    'VertexMode': lib.VertexMode.values,
    'VerticalDirection': lib.VerticalDirection.values,
    'WidgetInspectorServiceExtensions': lib.WidgetInspectorServiceExtensions.values,
    'WidgetsServiceExtensions': lib.WidgetsServiceExtensions.values,
    'WidgetState': lib.WidgetState.values,
    'WrapAlignment': lib.WrapAlignment.values,
    'WrapCrossAlignment': lib.WrapCrossAlignment.values,
  };
 
  @override
  final Map<String, Map<String, Object? Function()>> statics = {
    'Alignment': {
      'bottomCenter': () => lib.Alignment.bottomCenter,
      'bottomLeft': () => lib.Alignment.bottomLeft,
      'bottomRight': () => lib.Alignment.bottomRight,
      'center': () => lib.Alignment.center,
      'centerLeft': () => lib.Alignment.centerLeft,
      'centerRight': () => lib.Alignment.centerRight,
      'topCenter': () => lib.Alignment.topCenter,
      'topLeft': () => lib.Alignment.topLeft,
      'topRight': () => lib.Alignment.topRight,
    },
    'AlignmentDirectional': {
      'bottomCenter': () => lib.AlignmentDirectional.bottomCenter,
      'bottomEnd': () => lib.AlignmentDirectional.bottomEnd,
      'bottomStart': () => lib.AlignmentDirectional.bottomStart,
      'center': () => lib.AlignmentDirectional.center,
      'centerEnd': () => lib.AlignmentDirectional.centerEnd,
      'centerStart': () => lib.AlignmentDirectional.centerStart,
      'topCenter': () => lib.AlignmentDirectional.topCenter,
      'topEnd': () => lib.AlignmentDirectional.topEnd,
      'topStart': () => lib.AlignmentDirectional.topStart,
    },
    'AnimationStyle': {
      'noAnimation': () => lib.AnimationStyle.noAnimation,
    },
    'AutofillHints': {
      'addressCity': () => lib.AutofillHints.addressCity,
      'addressCityAndState': () => lib.AutofillHints.addressCityAndState,
      'addressState': () => lib.AutofillHints.addressState,
      'birthday': () => lib.AutofillHints.birthday,
      'birthdayDay': () => lib.AutofillHints.birthdayDay,
      'birthdayMonth': () => lib.AutofillHints.birthdayMonth,
      'birthdayYear': () => lib.AutofillHints.birthdayYear,
      'countryCode': () => lib.AutofillHints.countryCode,
      'countryName': () => lib.AutofillHints.countryName,
      'creditCardExpirationDate': () => lib.AutofillHints.creditCardExpirationDate,
      'creditCardExpirationDay': () => lib.AutofillHints.creditCardExpirationDay,
      'creditCardExpirationMonth': () => lib.AutofillHints.creditCardExpirationMonth,
      'creditCardExpirationYear': () => lib.AutofillHints.creditCardExpirationYear,
      'creditCardFamilyName': () => lib.AutofillHints.creditCardFamilyName,
      'creditCardGivenName': () => lib.AutofillHints.creditCardGivenName,
      'creditCardMiddleName': () => lib.AutofillHints.creditCardMiddleName,
      'creditCardName': () => lib.AutofillHints.creditCardName,
      'creditCardNumber': () => lib.AutofillHints.creditCardNumber,
      'creditCardSecurityCode': () => lib.AutofillHints.creditCardSecurityCode,
      'creditCardType': () => lib.AutofillHints.creditCardType,
      'email': () => lib.AutofillHints.email,
      'familyName': () => lib.AutofillHints.familyName,
      'fullStreetAddress': () => lib.AutofillHints.fullStreetAddress,
      'gender': () => lib.AutofillHints.gender,
      'givenName': () => lib.AutofillHints.givenName,
      'impp': () => lib.AutofillHints.impp,
      'jobTitle': () => lib.AutofillHints.jobTitle,
      'language': () => lib.AutofillHints.language,
      'location': () => lib.AutofillHints.location,
      'middleInitial': () => lib.AutofillHints.middleInitial,
      'middleName': () => lib.AutofillHints.middleName,
      'name': () => lib.AutofillHints.name,
      'namePrefix': () => lib.AutofillHints.namePrefix,
      'nameSuffix': () => lib.AutofillHints.nameSuffix,
      'newPassword': () => lib.AutofillHints.newPassword,
      'newUsername': () => lib.AutofillHints.newUsername,
      'nickname': () => lib.AutofillHints.nickname,
      'oneTimeCode': () => lib.AutofillHints.oneTimeCode,
      'organizationName': () => lib.AutofillHints.organizationName,
      'password': () => lib.AutofillHints.password,
      'photo': () => lib.AutofillHints.photo,
      'postalAddress': () => lib.AutofillHints.postalAddress,
      'postalAddressExtended': () => lib.AutofillHints.postalAddressExtended,
      'postalAddressExtendedPostalCode': () => lib.AutofillHints.postalAddressExtendedPostalCode,
      'postalCode': () => lib.AutofillHints.postalCode,
      'streetAddressLevel1': () => lib.AutofillHints.streetAddressLevel1,
      'streetAddressLevel2': () => lib.AutofillHints.streetAddressLevel2,
      'streetAddressLevel3': () => lib.AutofillHints.streetAddressLevel3,
      'streetAddressLevel4': () => lib.AutofillHints.streetAddressLevel4,
      'streetAddressLine1': () => lib.AutofillHints.streetAddressLine1,
      'streetAddressLine2': () => lib.AutofillHints.streetAddressLine2,
      'streetAddressLine3': () => lib.AutofillHints.streetAddressLine3,
      'sublocality': () => lib.AutofillHints.sublocality,
      'telephoneNumber': () => lib.AutofillHints.telephoneNumber,
      'telephoneNumberAreaCode': () => lib.AutofillHints.telephoneNumberAreaCode,
      'telephoneNumberCountryCode': () => lib.AutofillHints.telephoneNumberCountryCode,
      'telephoneNumberDevice': () => lib.AutofillHints.telephoneNumberDevice,
      'telephoneNumberExtension': () => lib.AutofillHints.telephoneNumberExtension,
      'telephoneNumberLocal': () => lib.AutofillHints.telephoneNumberLocal,
      'telephoneNumberLocalPrefix': () => lib.AutofillHints.telephoneNumberLocalPrefix,
      'telephoneNumberLocalSuffix': () => lib.AutofillHints.telephoneNumberLocalSuffix,
      'telephoneNumberNational': () => lib.AutofillHints.telephoneNumberNational,
      'transactionAmount': () => lib.AutofillHints.transactionAmount,
      'transactionCurrency': () => lib.AutofillHints.transactionCurrency,
      'url': () => lib.AutofillHints.url,
      'username': () => lib.AutofillHints.username,
    },
    'BorderRadius': {
      'zero': () => lib.BorderRadius.zero,
    },
    'BorderRadiusDirectional': {
      'zero': () => lib.BorderRadiusDirectional.zero,
    },
    'BorderSide': {
      'none': () => lib.BorderSide.none,
      'strokeAlignCenter': () => lib.BorderSide.strokeAlignCenter,
      'strokeAlignInside': () => lib.BorderSide.strokeAlignInside,
      'strokeAlignOutside': () => lib.BorderSide.strokeAlignOutside,
    },
    'BouncingScrollSimulation': {
      'maxSpringTransferVelocity': () => lib.BouncingScrollSimulation.maxSpringTransferVelocity,
    },
    'Characters': {
      'empty': () => lib.Characters.empty,
    },
    'ChildVicinity': {
      'invalid': () => lib.ChildVicinity.invalid,
    },
    'CopySelectionTextIntent': {
      'copy': () => lib.CopySelectionTextIntent.copy,
    },
    'Curves': {
      'bounceIn': () => lib.Curves.bounceIn,
      'bounceInOut': () => lib.Curves.bounceInOut,
      'bounceOut': () => lib.Curves.bounceOut,
      'decelerate': () => lib.Curves.decelerate,
      'ease': () => lib.Curves.ease,
      'easeIn': () => lib.Curves.easeIn,
      'easeInBack': () => lib.Curves.easeInBack,
      'easeInCirc': () => lib.Curves.easeInCirc,
      'easeInCubic': () => lib.Curves.easeInCubic,
      'easeInExpo': () => lib.Curves.easeInExpo,
      'easeInOut': () => lib.Curves.easeInOut,
      'easeInOutBack': () => lib.Curves.easeInOutBack,
      'easeInOutCirc': () => lib.Curves.easeInOutCirc,
      'easeInOutCubic': () => lib.Curves.easeInOutCubic,
      'easeInOutCubicEmphasized': () => lib.Curves.easeInOutCubicEmphasized,
      'easeInOutExpo': () => lib.Curves.easeInOutExpo,
      'easeInOutQuad': () => lib.Curves.easeInOutQuad,
      'easeInOutQuart': () => lib.Curves.easeInOutQuart,
      'easeInOutQuint': () => lib.Curves.easeInOutQuint,
      'easeInOutSine': () => lib.Curves.easeInOutSine,
      'easeInQuad': () => lib.Curves.easeInQuad,
      'easeInQuart': () => lib.Curves.easeInQuart,
      'easeInQuint': () => lib.Curves.easeInQuint,
      'easeInSine': () => lib.Curves.easeInSine,
      'easeInToLinear': () => lib.Curves.easeInToLinear,
      'easeOut': () => lib.Curves.easeOut,
      'easeOutBack': () => lib.Curves.easeOutBack,
      'easeOutCirc': () => lib.Curves.easeOutCirc,
      'easeOutCubic': () => lib.Curves.easeOutCubic,
      'easeOutExpo': () => lib.Curves.easeOutExpo,
      'easeOutQuad': () => lib.Curves.easeOutQuad,
      'easeOutQuart': () => lib.Curves.easeOutQuart,
      'easeOutQuint': () => lib.Curves.easeOutQuint,
      'easeOutSine': () => lib.Curves.easeOutSine,
      'elasticIn': () => lib.Curves.elasticIn,
      'elasticInOut': () => lib.Curves.elasticInOut,
      'elasticOut': () => lib.Curves.elasticOut,
      'fastEaseInToSlowEaseOut': () => lib.Curves.fastEaseInToSlowEaseOut,
      'fastLinearToSlowEaseIn': () => lib.Curves.fastLinearToSlowEaseIn,
      'fastOutSlowIn': () => lib.Curves.fastOutSlowIn,
      'linear': () => lib.Curves.linear,
      'linearToEaseOut': () => lib.Curves.linearToEaseOut,
      'slowMiddle': () => lib.Curves.slowMiddle,
    },
    'DefaultSelectionStyle': {
      'defaultColor': () => lib.DefaultSelectionStyle.defaultColor,
    },
    'DefaultWidgetsLocalizations': {
      'delegate': () => lib.DefaultWidgetsLocalizations.delegate,
    },
    'EdgeInsets': {
      'zero': () => lib.EdgeInsets.zero,
    },
    'EdgeInsetsDirectional': {
      'zero': () => lib.EdgeInsetsDirectional.zero,
    },
    'EdgeInsetsGeometry': {
      'infinity': () => lib.EdgeInsetsGeometry.infinity,
    },
    'EditableText': {
      'debugDeterministicCursor': () => lib.EditableText.debugDeterministicCursor,
    },
    'ErrorWidget': {
      'builder': () => lib.ErrorWidget.builder,
    },
    'FlutterErrorDetails': {
      'propertiesTransformers': () => lib.FlutterErrorDetails.propertiesTransformers,
    },
    'FocusManager': {
      'instance': () => lib.FocusManager.instance,
    },
    'FontWeight': {
      'bold': () => lib.FontWeight.bold,
      'normal': () => lib.FontWeight.normal,
      'values': () => lib.FontWeight.values,
      'w100': () => lib.FontWeight.w100,
      'w200': () => lib.FontWeight.w200,
      'w300': () => lib.FontWeight.w300,
      'w400': () => lib.FontWeight.w400,
      'w500': () => lib.FontWeight.w500,
      'w600': () => lib.FontWeight.w600,
      'w700': () => lib.FontWeight.w700,
      'w800': () => lib.FontWeight.w800,
      'w900': () => lib.FontWeight.w900,
    },
    'FractionalOffset': {
      'bottomCenter': () => lib.FractionalOffset.bottomCenter,
      'bottomLeft': () => lib.FractionalOffset.bottomLeft,
      'bottomRight': () => lib.FractionalOffset.bottomRight,
      'center': () => lib.FractionalOffset.center,
      'centerLeft': () => lib.FractionalOffset.centerLeft,
      'centerRight': () => lib.FractionalOffset.centerRight,
      'topCenter': () => lib.FractionalOffset.topCenter,
      'topLeft': () => lib.FractionalOffset.topLeft,
      'topRight': () => lib.FractionalOffset.topRight,
    },
    'FutureBuilder': {
      'debugRethrowError': () => lib.FutureBuilder.debugRethrowError,
    },
    'ImageConfiguration': {
      'empty': () => lib.ImageConfiguration.empty,
    },
    'InlineSpanSemanticsInformation': {
      'placeholder': () => lib.InlineSpanSemanticsInformation.placeholder,
    },
    'Intent': {
      'doNothing': () => lib.Intent.doNothing,
    },
    'LinearBorder': {
      'none': () => lib.LinearBorder.none,
    },
    'MagnifierInfo': {
      'empty': () => lib.MagnifierInfo.empty,
    },
    'MouseCursor': {
      'defer': () => lib.MouseCursor.defer,
      'uncontrolled': () => lib.MouseCursor.uncontrolled,
    },
    'NavigationToolbar': {
      'kMiddleSpacing': () => lib.NavigationToolbar.kMiddleSpacing,
    },
    'Navigator': {
      'defaultRouteName': () => lib.Navigator.defaultRouteName,
    },
    'Offset': {
      'infinite': () => lib.Offset.infinite,
      'zero': () => lib.Offset.zero,
    },
    'PlaceholderDimensions': {
      'empty': () => lib.PlaceholderDimensions.empty,
    },
    'PlaceholderSpan': {
      'placeholderCodeUnit': () => lib.PlaceholderSpan.placeholderCodeUnit,
    },
    'PlatformSelectableRegionContextMenu': {
      'debugOverrideRegisterViewFactory': () => lib.PlatformSelectableRegionContextMenu.debugOverrideRegisterViewFactory,
    },
    'Radius': {
      'zero': () => lib.Radius.zero,
    },
    'Rect': {
      'largest': () => lib.Rect.largest,
      'zero': () => lib.Rect.zero,
    },
    'RelativeRect': {
      'fill': () => lib.RelativeRect.fill,
    },
    'RenderObject': {
      'debugActiveLayout': () => lib.RenderObject.debugActiveLayout,
      'debugActivePaint': () => lib.RenderObject.debugActivePaint,
      'debugCheckingIntrinsics': () => lib.RenderObject.debugCheckingIntrinsics,
    },
    'RRect': {
      'zero': () => lib.RRect.zero,
    },
    'ScrollDragController': {
      'momentumRetainStationaryDurationThreshold': () => lib.ScrollDragController.momentumRetainStationaryDurationThreshold,
      'momentumRetainVelocityThresholdFactor': () => lib.ScrollDragController.momentumRetainVelocityThresholdFactor,
      'motionStoppedDurationThreshold': () => lib.ScrollDragController.motionStoppedDurationThreshold,
    },
    'SelectionOverlay': {
      'fadeDuration': () => lib.SelectionOverlay.fadeDuration,
    },
    'Size': {
      'infinite': () => lib.Size.infinite,
      'zero': () => lib.Size.zero,
    },
    'StrutStyle': {
      'disabled': () => lib.StrutStyle.disabled,
    },
    'SystemMouseCursors': {
      'alias': () => lib.SystemMouseCursors.alias,
      'allScroll': () => lib.SystemMouseCursors.allScroll,
      'basic': () => lib.SystemMouseCursors.basic,
      'cell': () => lib.SystemMouseCursors.cell,
      'click': () => lib.SystemMouseCursors.click,
      'contextMenu': () => lib.SystemMouseCursors.contextMenu,
      'copy': () => lib.SystemMouseCursors.copy,
      'disappearing': () => lib.SystemMouseCursors.disappearing,
      'forbidden': () => lib.SystemMouseCursors.forbidden,
      'grab': () => lib.SystemMouseCursors.grab,
      'grabbing': () => lib.SystemMouseCursors.grabbing,
      'help': () => lib.SystemMouseCursors.help,
      'move': () => lib.SystemMouseCursors.move,
      'noDrop': () => lib.SystemMouseCursors.noDrop,
      'none': () => lib.SystemMouseCursors.none,
      'precise': () => lib.SystemMouseCursors.precise,
      'progress': () => lib.SystemMouseCursors.progress,
      'resizeColumn': () => lib.SystemMouseCursors.resizeColumn,
      'resizeDown': () => lib.SystemMouseCursors.resizeDown,
      'resizeDownLeft': () => lib.SystemMouseCursors.resizeDownLeft,
      'resizeDownRight': () => lib.SystemMouseCursors.resizeDownRight,
      'resizeLeft': () => lib.SystemMouseCursors.resizeLeft,
      'resizeLeftRight': () => lib.SystemMouseCursors.resizeLeftRight,
      'resizeRight': () => lib.SystemMouseCursors.resizeRight,
      'resizeRow': () => lib.SystemMouseCursors.resizeRow,
      'resizeUp': () => lib.SystemMouseCursors.resizeUp,
      'resizeUpDown': () => lib.SystemMouseCursors.resizeUpDown,
      'resizeUpLeft': () => lib.SystemMouseCursors.resizeUpLeft,
      'resizeUpLeftDownRight': () => lib.SystemMouseCursors.resizeUpLeftDownRight,
      'resizeUpRight': () => lib.SystemMouseCursors.resizeUpRight,
      'resizeUpRightDownLeft': () => lib.SystemMouseCursors.resizeUpRightDownLeft,
      'text': () => lib.SystemMouseCursors.text,
      'verticalText': () => lib.SystemMouseCursors.verticalText,
      'wait': () => lib.SystemMouseCursors.wait,
      'zoomIn': () => lib.SystemMouseCursors.zoomIn,
      'zoomOut': () => lib.SystemMouseCursors.zoomOut,
    },
    'TextAlignVertical': {
      'bottom': () => lib.TextAlignVertical.bottom,
      'center': () => lib.TextAlignVertical.center,
      'top': () => lib.TextAlignVertical.top,
    },
    'TextDecoration': {
      'lineThrough': () => lib.TextDecoration.lineThrough,
      'none': () => lib.TextDecoration.none,
      'overline': () => lib.TextDecoration.overline,
      'underline': () => lib.TextDecoration.underline,
    },
    'TextEditingValue': {
      'empty': () => lib.TextEditingValue.empty,
    },
    'TextInputType': {
      'datetime': () => lib.TextInputType.datetime,
      'emailAddress': () => lib.TextInputType.emailAddress,
      'multiline': () => lib.TextInputType.multiline,
      'name': () => lib.TextInputType.name,
      'none': () => lib.TextInputType.none,
      'number': () => lib.TextInputType.number,
      'phone': () => lib.TextInputType.phone,
      'streetAddress': () => lib.TextInputType.streetAddress,
      'text': () => lib.TextInputType.text,
      'url': () => lib.TextInputType.url,
      'values': () => lib.TextInputType.values,
      'visiblePassword': () => lib.TextInputType.visiblePassword,
    },
    'TextMagnifierConfiguration': {
      'disabled': () => lib.TextMagnifierConfiguration.disabled,
    },
    'TextRange': {
      'empty': () => lib.TextRange.empty,
    },
    'TextScaler': {
      'noScaling': () => lib.TextScaler.noScaling,
    },
    'Tolerance': {
      'defaultTolerance': () => lib.Tolerance.defaultTolerance,
    },
    'ToolbarOptions': {
      'empty': () => lib.ToolbarOptions.empty,
    },
    'TreeSliver': {
      'defaultAnimationCurve': () => lib.TreeSliver.defaultAnimationCurve,
      'defaultAnimationDuration': () => lib.TreeSliver.defaultAnimationDuration,
      'defaultToggleAnimationStyle': () => lib.TreeSliver.defaultToggleAnimationStyle,
    },
    'UndoHistoryValue': {
      'empty': () => lib.UndoHistoryValue.empty,
    },
    'Velocity': {
      'zero': () => lib.Velocity.zero,
    },
    'WidgetsApp': {
      'debugAllowBannerOverride': () => lib.WidgetsApp.debugAllowBannerOverride,
      'debugShowWidgetInspectorOverride': () => lib.WidgetsApp.debugShowWidgetInspectorOverride,
      'defaultActions': () => lib.WidgetsApp.defaultActions,
      'defaultShortcuts': () => lib.WidgetsApp.defaultShortcuts,
      'showPerformanceOverlayOverride': () => lib.WidgetsApp.showPerformanceOverlayOverride,
    },
    'WidgetStateColor': {
      'transparent': () => lib.WidgetStateColor.transparent,
    },
    'WidgetStateMouseCursor': {
      'clickable': () => lib.WidgetStateMouseCursor.clickable,
      'textable': () => lib.WidgetStateMouseCursor.textable,
    },
  };
}
